-- +goose Up

-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS ltree;
-- +goose StatementEnd

-- ------------------------------------------------------------
-- 1. MASTER DATA: SKUS, PACKAGING & LOTS
-- ------------------------------------------------------------

CREATE TYPE uom AS ENUM (
    'EACH',
    'Kg',
    'g',
    'm',
    'L',
    'mL'
);

CREATE TABLE stock_keeping_units (
    id bigint 
        GENERATED ALWAYS AS IDENTITY (START WITH 10000) 
        PRIMARY KEY,
    sku_code text COLLATE "C" NOT NULL UNIQUE,
    name text NOT NULL,
    base_uom uom NOT NULL DEFAULT 'EACH',
    is_discrete boolean NOT NULL DEFAULT true,
    requires_lot_tracking boolean NOT NULL DEFAULT false,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_skus_name_trgm ON stock_keeping_units USING gin (name gin_trgm_ops);
CREATE INDEX idx_skus_attributes ON stock_keeping_units USING gin (attributes);

CREATE TABLE sku_packaging_units (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sku_id bigint NOT NULL REFERENCES stock_keeping_units(id) ON DELETE CASCADE,
    unit_name text NOT NULL,
    conversion_factor numeric(12, 4) NOT NULL CHECK (conversion_factor > 0),
    parent_packaging_unit_id bigint,
    is_base_unit boolean NOT NULL DEFAULT false,
    allows_break_bulk boolean NOT NULL DEFAULT false,
    barcode text COLLATE "C" UNIQUE,
    tare_weight_kg numeric(10, 3) CHECK (tare_weight_kg >= 0),
    gross_volume_cm3 numeric(12, 2) CHECK (gross_volume_cm3 > 0),

    CONSTRAINT uq_sku_unit_name UNIQUE (sku_id, unit_name),
    CONSTRAINT uq_sku_packaging_units_id_sku UNIQUE (id, sku_id),

    CONSTRAINT chk_base_unit_factor CHECK (
        NOT is_base_unit OR conversion_factor = 1.0000
    ),
    CONSTRAINT fk_pku_same_sku_parent 
        FOREIGN KEY (parent_packaging_unit_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT chk_base_unit_no_parent CHECK (
        NOT is_base_unit OR parent_packaging_unit_id IS NULL
    ),
    CONSTRAINT chk_no_self_parent CHECK (
        parent_packaging_unit_id IS NULL OR parent_packaging_unit_id != id
    )
);

CREATE UNIQUE INDEX uq_sku_single_base_unit 
    ON sku_packaging_units (sku_id) 
    WHERE is_base_unit = true;

CREATE INDEX idx_packaging_units_sku ON sku_packaging_units (sku_id);

CREATE TYPE lot_status AS ENUM (
    'AVAILABLE',
    'QUARANTINED',
    'EXPIRED',
    'RECALLED'
);

CREATE TABLE lots (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    lot_number text COLLATE "C" NOT NULL,
    status lot_status NOT NULL DEFAULT 'AVAILABLE',
    manufactured_at date,
    expires_at date,
    received_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_sku_lot_number UNIQUE (sku_id, lot_number),
    CONSTRAINT uq_sku_lot_id UNIQUE (id, sku_id)
);

CREATE INDEX idx_lots_expiration ON lots (expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_lots_status ON lots (status);

-- ------------------------------------------------------------
-- 2. UNIFIED STORAGE HIERARCHY (BINS, PALLETS & TOTES)
-- ------------------------------------------------------------

CREATE TYPE storage_node_type AS ENUM (
    'WAREHOUSE',
    'ZONE',
    'AISLE',
    'BAY',
    'BIN',       -- Immobile physical locations
    'PALLET',
    'TOTE',
    'CART'       -- Mobile handling units
);

CREATE TABLE storage_nodes (
    id bigint 
        GENERATED BY DEFAULT AS IDENTITY 
        PRIMARY KEY,
    parent_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    path ltree NOT NULL,
    code text COLLATE "C" NOT NULL UNIQUE,
    node_type storage_node_type NOT NULL DEFAULT 'BIN',
    is_movable boolean NOT NULL DEFAULT false,
    max_weight_kg numeric(10, 2) CHECK (max_weight_kg > 0),
    max_volume_cm3 numeric(12, 2) CHECK (max_volume_cm3 > 0),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_storage_nodes_path_gist ON storage_nodes USING gist (path);
CREATE INDEX idx_storage_nodes_path_btree ON storage_nodes (path);
CREATE INDEX idx_storage_nodes_parent_id ON storage_nodes (parent_id);
CREATE INDEX idx_storage_nodes_type ON storage_nodes (node_type);

-- ------------------------------------------------------------
-- 3. INVENTORY BALANCES
-- ------------------------------------------------------------

CREATE TABLE inventory_balances (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    node_id bigint NOT NULL 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    lot_id bigint,

    is_sealed boolean NOT NULL DEFAULT true,
    package_count numeric(12, 4) NOT NULL DEFAULT 1 CHECK (package_count >= 0),

    -- Quantities always stored in the SKU's atomic base UOM
    on_hand numeric(12, 4) NOT NULL DEFAULT 0,
    allocated numeric(12, 4) NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_on_hand_positive CHECK (on_hand >= 0),
    CONSTRAINT chk_allocated_positive CHECK (allocated >= 0),
    CONSTRAINT chk_allocated_le_on_hand CHECK (allocated <= on_hand),

    -- Composite foreign keys prevent cross-SKU lot/PKU mixing
    CONSTRAINT fk_balance_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT fk_balance_lot 
        FOREIGN KEY (lot_id, sku_id) 
        REFERENCES lots(id, sku_id) 
        ON DELETE RESTRICT
);

-- Unique entry per Node + PKU + Lot + Sealed State
CREATE UNIQUE INDEX uq_node_inventory 
    ON inventory_balances (node_id, pku_id, lot_id, is_sealed) NULLS NOT DISTINCT;

-- Fast index for reservation and picking engine
CREATE INDEX idx_balances_reservable 
    ON inventory_balances (sku_id, pku_id, is_sealed, lot_id, on_hand, allocated) 
    WHERE (on_hand - allocated) > 0;

CREATE INDEX idx_balances_node ON inventory_balances (node_id);

-- ------------------------------------------------------------
-- 4. OUTBOUND DEMAND & ALLOCATION ENGINE
-- ------------------------------------------------------------

CREATE TYPE order_status AS ENUM (
    'PENDING',
    'ALLOCATED',
    'PARTIALLY_ALLOCATED',
    'PICKING',
    'PACKED',
    'SHIPPED',
    'CANCELLED'
);

CREATE TABLE outbound_orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_number text COLLATE "C" NOT NULL UNIQUE,
    customer_name text,
    status order_status NOT NULL DEFAULT 'PENDING',
    priority integer NOT NULL DEFAULT 100,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_status_priority 
    ON outbound_orders (status, priority DESC, created_at ASC);

CREATE TABLE outbound_order_lines (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL 
        REFERENCES outbound_orders(id) 
        ON DELETE CASCADE,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    requested_quantity numeric(12, 4) NOT NULL CHECK (requested_quantity > 0),
    fulfilled_quantity numeric(12, 4) NOT NULL DEFAULT 0 CHECK (fulfilled_quantity >= 0),

    CONSTRAINT fk_order_line_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT uq_order_line_pku UNIQUE (order_id, pku_id),
    CONSTRAINT chk_fulfillment_bounds CHECK (fulfilled_quantity <= requested_quantity)
);

CREATE INDEX idx_order_lines_order ON outbound_order_lines (order_id);
CREATE INDEX idx_order_lines_sku ON outbound_order_lines (sku_id);
CREATE INDEX idx_order_lines_pku ON outbound_order_lines (pku_id);

CREATE TABLE inventory_allocations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_line_id bigint NOT NULL 
        REFERENCES outbound_order_lines(id) 
        ON DELETE CASCADE,
    balance_id bigint NOT NULL 
        REFERENCES inventory_balances(id) 
        ON DELETE RESTRICT,
    allocated_quantity numeric(12, 4) NOT NULL CHECK (allocated_quantity > 0),
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_order_line_balance UNIQUE (order_line_id, balance_id)
);

CREATE INDEX idx_allocations_order_line ON inventory_allocations (order_line_id);
CREATE INDEX idx_allocations_balance ON inventory_allocations (balance_id);

-- ------------------------------------------------------------
-- 5. MOVEMENTS & AUDIT LEDGER
-- ------------------------------------------------------------

CREATE TYPE movement_reason AS ENUM (
    'RECEIVING',
    'PUTAWAY',
    'PICK',
    'REPLENISHMENT',
    'INTERNAL_TRANSFER',
    'BREAK_PACKAGE',
    'REPACKAGE',
    'CYCLE_COUNT',
    'SCRAP_DAMAGED',
    'RETURN'
);

CREATE TABLE inventory_movements (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    lot_id bigint,
    package_count numeric(12, 4) NOT NULL DEFAULT 1 CHECK (package_count >= 0),
    quantity numeric(12, 4) NOT NULL CHECK (quantity > 0),

    source_node_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    destination_node_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,

    reason movement_reason NOT NULL,
    reference_id text COLLATE "C",
    allocation_id bigint 
        REFERENCES inventory_allocations(id) 
        ON DELETE RESTRICT,
    is_sealed boolean NOT NULL DEFAULT true,
    operator_id text COLLATE "C" NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_movement_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT fk_movement_lot 
        FOREIGN KEY (lot_id, sku_id) 
        REFERENCES lots(id, sku_id) 
        ON DELETE RESTRICT,

    CONSTRAINT chk_movement_endpoints CHECK (
        source_node_id IS NOT NULL OR destination_node_id IS NOT NULL
    ),
    CONSTRAINT chk_movement_distinct_endpoints CHECK (
        source_node_id IS NULL OR destination_node_id IS NULL OR source_node_id != destination_node_id
    )
);

CREATE INDEX idx_movements_sku ON inventory_movements (sku_id, created_at DESC);
CREATE INDEX idx_movements_pku ON inventory_movements (pku_id, created_at DESC);
CREATE INDEX idx_movements_lot ON inventory_movements (lot_id, created_at DESC);
CREATE INDEX idx_movements_source ON inventory_movements (source_node_id, created_at DESC) WHERE source_node_id IS NOT NULL;
CREATE INDEX idx_movements_dest ON inventory_movements (destination_node_id, created_at DESC) WHERE destination_node_id IS NOT NULL;
CREATE INDEX idx_movements_allocation ON inventory_movements (allocation_id) WHERE allocation_id IS NOT NULL;

-- ------------------------------------------------------------
-- 6. INBOUND PROCUREMENT & TASKS
-- ------------------------------------------------------------

CREATE TYPE inbound_order_status AS ENUM (
    'DRAFT',
    'ISSUED',
    'PARTIALLY_RECEIVED',
    'RECEIVED',
    'CANCELLED'
);

CREATE TABLE inbound_orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    po_number text COLLATE "C" NOT NULL UNIQUE,
    vendor_name text NOT NULL,
    status inbound_order_status NOT NULL DEFAULT 'ISSUED',
    expected_delivery date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE inbound_order_lines (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inbound_order_id bigint NOT NULL 
        REFERENCES inbound_orders(id) 
        ON DELETE CASCADE,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    expected_quantity numeric(12, 4) NOT NULL CHECK (expected_quantity > 0),
    received_quantity numeric(12, 4) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),

    CONSTRAINT fk_po_line_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT uq_po_line_pku UNIQUE (inbound_order_id, pku_id)
);

CREATE INDEX idx_po_lines_po ON inbound_order_lines (inbound_order_id);
CREATE INDEX idx_po_lines_sku ON inbound_order_lines (sku_id);

CREATE TYPE task_type AS ENUM (
    'PUTAWAY',
    'PICK',
    'REPLENISH',
    'COUNT',
    'RELOCATE_NODE'
);

CREATE TYPE task_status AS ENUM (
    'PENDING',
    'ASSIGNED',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);

CREATE TABLE warehouse_tasks (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    task_type task_type NOT NULL,
    status task_status NOT NULL DEFAULT 'PENDING',
    priority integer NOT NULL DEFAULT 100,

    -- Stock-level directives
    sku_id bigint REFERENCES stock_keeping_units(id) ON DELETE RESTRICT,
    pku_id bigint REFERENCES sku_packaging_units(id) ON DELETE RESTRICT,
    lot_id bigint REFERENCES lots(id) ON DELETE RESTRICT,
    package_count numeric(12, 4) CHECK (package_count > 0),
    quantity numeric(12, 4) CHECK (quantity > 0),

    -- Container-level directives (e.g. moving an entire pallet)
    target_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,

    source_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    destination_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,

    order_line_id bigint REFERENCES outbound_order_lines(id) ON DELETE SET NULL,
    allocation_id bigint REFERENCES inventory_allocations(id) ON DELETE SET NULL,

    assigned_operator_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,

    CONSTRAINT chk_task_payload CHECK (
        target_node_id IS NOT NULL OR (pku_id IS NOT NULL AND quantity IS NOT NULL)
    )
);

CREATE INDEX idx_tasks_execution ON warehouse_tasks (status, priority DESC, created_at ASC);
CREATE INDEX idx_tasks_operator ON warehouse_tasks (assigned_operator_id) WHERE assigned_operator_id IS NOT NULL;

-- ------------------------------------------------------------
-- 7. ESSENTIAL DATABASE INTEGRITY TRIGGERS
-- ------------------------------------------------------------

-- A. Maintain storage_node ltree path on creation
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_storage_node_path()
RETURNS TRIGGER AS $func$
DECLARE
    parent_path ltree;
BEGIN
    IF NEW.parent_id IS NULL THEN
        NEW.path := text2ltree(NEW.id::text);
        RETURN NEW;
    END IF;

    SELECT path INTO parent_path 
    FROM storage_nodes 
    WHERE id = NEW.parent_id;

    IF parent_path IS NULL THEN
        RAISE EXCEPTION 'Parent storage node ID % does not exist', NEW.parent_id;
    END IF;

    NEW.path := parent_path || text2ltree(NEW.id::text);
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_set_storage_node_path
BEFORE INSERT ON storage_nodes
FOR EACH ROW
EXECUTE FUNCTION set_storage_node_path();

-- B. Recompute path and guard against cycles when reparenting
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION update_storage_node_parent_change()
RETURNS TRIGGER AS $func$
DECLARE
    parent_path ltree;
BEGIN
    IF NEW.parent_id IS NULL THEN
        NEW.path := text2ltree(NEW.id::text);
        RETURN NEW;
    END IF;

    IF NEW.parent_id = NEW.id THEN
        RAISE EXCEPTION 'Storage node % cannot be its own parent', NEW.id;
    END IF;

    SELECT path INTO parent_path 
    FROM storage_nodes 
    WHERE id = NEW.parent_id;

    IF parent_path IS NULL THEN
        RAISE EXCEPTION 'Parent storage node ID % does not exist', NEW.parent_id;
    END IF;

    -- Cycle check: parent cannot be inside this node's own subtree
    IF parent_path <@ OLD.path THEN
        RAISE EXCEPTION 'Cyclic hierarchy detected: Node % cannot be moved into its descendant branch (Node %)',
            NEW.id, NEW.parent_id;
    END IF;

    NEW.path := parent_path || text2ltree(NEW.id::text);
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_update_storage_node_parent_change
BEFORE UPDATE OF parent_id ON storage_nodes
FOR EACH ROW
WHEN (OLD.parent_id IS DISTINCT FROM NEW.parent_id)
EXECUTE FUNCTION update_storage_node_parent_change();

-- C. Cascade path updates down to all descendants
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION update_storage_node_subtree_path()
RETURNS TRIGGER AS $func$
BEGIN
    IF pg_trigger_depth() > 1 THEN
        RETURN NEW;
    END IF;

    UPDATE storage_nodes
    SET path = NEW.path || subpath(path, nlevel(OLD.path))
    WHERE path <@ OLD.path AND id != OLD.id;

    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_update_storage_node_subtree_path
AFTER UPDATE OF path ON storage_nodes
FOR EACH ROW
WHEN (OLD.path IS DISTINCT FROM NEW.path)
EXECUTE FUNCTION update_storage_node_subtree_path();

-- D. Audit Immutability Trigger
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION prevent_movement_mutation()
RETURNS TRIGGER AS $func$
BEGIN
    RAISE EXCEPTION 'Audit violation: inventory_movements is append-only and cannot be updated or deleted.';
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_protect_inventory_movements
BEFORE UPDATE OR DELETE ON inventory_movements
FOR EACH ROW
EXECUTE FUNCTION prevent_movement_mutation();

-- +goose Down
DROP TRIGGER IF EXISTS trg_protect_inventory_movements ON inventory_movements;
DROP FUNCTION IF EXISTS prevent_movement_mutation();

DROP TRIGGER IF EXISTS trg_update_storage_node_subtree_path ON storage_nodes;
DROP FUNCTION IF EXISTS update_storage_node_subtree_path();

DROP TRIGGER IF EXISTS trg_update_storage_node_parent_change ON storage_nodes;
DROP FUNCTION IF EXISTS update_storage_node_parent_change();

DROP TRIGGER IF EXISTS trg_set_storage_node_path ON storage_nodes;
DROP FUNCTION IF EXISTS set_storage_node_path();

DROP TABLE IF EXISTS warehouse_tasks;
DROP TYPE IF EXISTS task_status;
DROP TYPE IF EXISTS task_type;

DROP TABLE IF EXISTS inbound_order_lines;
DROP TABLE IF EXISTS inbound_orders;
DROP TYPE IF EXISTS inbound_order_status;

DROP TABLE IF EXISTS inventory_movements;
DROP TYPE IF EXISTS movement_reason;

DROP TABLE IF EXISTS inventory_allocations;
DROP TABLE IF EXISTS outbound_order_lines;
DROP TABLE IF EXISTS outbound_orders;
DROP TYPE IF EXISTS order_status;

DROP TABLE IF EXISTS inventory_balances;
DROP TABLE IF EXISTS storage_nodes;
DROP TYPE IF EXISTS storage_node_type;

DROP TABLE IF EXISTS lots;
DROP TYPE IF EXISTS lot_status;
DROP TABLE IF EXISTS sku_packaging_units;
DROP TABLE IF EXISTS stock_keeping_units;
DROP TYPE IF EXISTS uom;

-- +goose StatementBegin
DROP EXTENSION IF EXISTS ltree;
DROP EXTENSION IF EXISTS pg_trgm;
-- +goose StatementEnd
