-- +goose Up

-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS ltree;
-- +goose StatementEnd

-- ------------------------------------------------------------
-- 1. MASTER DATA: SKUS, PACKAGING & LOTS
-- ------------------------------------------------------------

CREATE TYPE uom AS ENUM (
    'EACH',
    'Kg',
    'g',
    'm',
    'L',
    'mL'
);

CREATE TABLE stock_keeping_units (
    id bigint 
        GENERATED ALWAYS AS IDENTITY (START WITH 10000) 
        PRIMARY KEY,
    name text NOT NULL,
    base_uom uom NOT NULL DEFAULT 'EACH',
    is_discrete boolean NOT NULL DEFAULT true,
    requires_lot_tracking boolean NOT NULL DEFAULT false,
    tenant_id bigint,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_skus_name_trgm ON stock_keeping_units USING gin (name gin_trgm_ops);
CREATE INDEX idx_skus_attributes ON stock_keeping_units USING gin (attributes);

CREATE TABLE sku_packaging_units (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sku_id bigint NOT NULL REFERENCES stock_keeping_units(id) ON DELETE CASCADE,
    unit_name text NOT NULL,
    conversion_factor numeric(12, 4) NOT NULL CHECK (conversion_factor > 0),
    parent_packaging_unit_id bigint,
    is_base_unit boolean NOT NULL DEFAULT false,
    allows_break_bulk boolean NOT NULL DEFAULT false,
    barcode text COLLATE "C" UNIQUE,
    tare_weight_kg numeric(10, 3) CHECK (tare_weight_kg >= 0),
    gross_volume_cm3 numeric(12, 2) CHECK (gross_volume_cm3 > 0),

    CONSTRAINT uq_sku_unit_name UNIQUE (sku_id, unit_name),
    CONSTRAINT uq_sku_packaging_units_id_sku UNIQUE (id, sku_id),

    CONSTRAINT chk_base_unit_factor CHECK (
        NOT is_base_unit OR conversion_factor = 1.0000
    ),
    CONSTRAINT fk_pku_same_sku_parent 
        FOREIGN KEY (parent_packaging_unit_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT chk_base_unit_no_parent CHECK (
        NOT is_base_unit OR parent_packaging_unit_id IS NULL
    ),
    CONSTRAINT chk_no_self_parent CHECK (
        parent_packaging_unit_id IS NULL OR parent_packaging_unit_id != id
    )
);

CREATE UNIQUE INDEX uq_sku_single_base_unit 
    ON sku_packaging_units (sku_id) 
    WHERE is_base_unit = true;

CREATE INDEX idx_packaging_units_sku ON sku_packaging_units (sku_id);

CREATE TYPE lot_status AS ENUM (
    'AVAILABLE',
    'QUARANTINED',
    'EXPIRED',
    'RECALLED'
);

CREATE TABLE lots (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    lot_number text COLLATE "C" NOT NULL,
    status lot_status NOT NULL DEFAULT 'AVAILABLE',
    manufactured_at date,
    expires_at date,
    received_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_sku_lot_number UNIQUE (sku_id, lot_number),
    CONSTRAINT uq_sku_lot_id UNIQUE (id, sku_id)
);

CREATE INDEX idx_lots_expiration ON lots (expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_lots_status ON lots (status);

-- ------------------------------------------------------------
-- 2. UNIFIED STORAGE HIERARCHY (BINS, PALLETS & TOTES)
-- ------------------------------------------------------------

CREATE TYPE storage_node_type AS ENUM (
    'WAREHOUSE',
    'ZONE',
    'AISLE',
    'BAY',
    'BIN',       -- Immobile physical locations
    'PALLET',
    'TOTE',
    'CART'       -- Mobile handling units
);

CREATE TABLE storage_nodes (
    id bigint 
        GENERATED BY DEFAULT AS IDENTITY 
        PRIMARY KEY,
    parent_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    path ltree,
    code text COLLATE "C" NOT NULL UNIQUE,
    node_type storage_node_type NOT NULL DEFAULT 'BIN',
    is_movable boolean NOT NULL DEFAULT false,
    max_weight_kg numeric(10, 2) CHECK (max_weight_kg > 0),
    max_volume_cm3 numeric(12, 2) CHECK (max_volume_cm3 > 0),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_storage_nodes_path_gist ON storage_nodes USING gist (path);
CREATE INDEX idx_storage_nodes_path_btree ON storage_nodes (path);
CREATE INDEX idx_storage_nodes_parent_id ON storage_nodes (parent_id);
CREATE INDEX idx_storage_nodes_type ON storage_nodes (node_type);

-- ------------------------------------------------------------
-- 3. INVENTORY BALANCES
-- ------------------------------------------------------------

CREATE TABLE inventory_balances (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    node_id bigint NOT NULL 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    lot_id bigint,

    is_sealed boolean NOT NULL DEFAULT true,
    package_count numeric(12, 4) NOT NULL CHECK (package_count >= 0),

    -- version for OCC
    version int NOT NULL DEFAULT 1,

    -- Quantities always stored in the SKU's atomic base UOM
    on_hand numeric(12, 4) NOT NULL DEFAULT 0,
    allocated numeric(12, 4) NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_on_hand_positive CHECK (on_hand >= 0),
    CONSTRAINT chk_allocated_positive CHECK (allocated >= 0),
    CONSTRAINT chk_allocated_le_on_hand CHECK (allocated <= on_hand),
    CONSTRAINT chk_unsealed_no_packages 
      CHECK (is_sealed OR package_count = 0),

    -- Composite foreign keys prevent cross-SKU lot/PKU mixing
    CONSTRAINT fk_balance_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT fk_balance_lot 
        FOREIGN KEY (lot_id, sku_id) 
        REFERENCES lots(id, sku_id) 
        ON DELETE RESTRICT,

    CONSTRAINT uq_balance_id_sku UNIQUE (id, sku_id)
);

ALTER TABLE inventory_balances SET (fillfactor = 70);

-- Unique entry per Node + PKU + Lot + Sealed State
CREATE UNIQUE INDEX uq_node_inventory 
    ON inventory_balances (node_id, pku_id, lot_id, is_sealed) NULLS NOT DISTINCT;

CREATE INDEX idx_balances_reservable 
    ON inventory_balances (sku_id, pku_id, is_sealed, lot_id);

CREATE INDEX idx_balances_node ON inventory_balances (node_id);

-- ------------------------------------------------------------
-- 4. OUTBOUND DEMAND & ALLOCATION ENGINE
-- ------------------------------------------------------------

CREATE TYPE order_status AS ENUM (
    'PENDING',
    'ALLOCATED',
    'PARTIALLY_ALLOCATED',
    'PICKING',
    'PACKED',
    'SHIPPED',
    'CANCELLED'
);

CREATE TABLE outbound_orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tenant_id bigint,
    order_number text COLLATE "C" NOT NULL UNIQUE,
    version integer NOT NULL DEFAULT 1,
    customer_name text,
    status order_status NOT NULL DEFAULT 'PENDING',
    priority integer NOT NULL DEFAULT 100,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_status_priority 
    ON outbound_orders (status, priority DESC, created_at ASC);

CREATE TABLE outbound_order_lines (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL 
        REFERENCES outbound_orders(id) 
        ON DELETE CASCADE,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    requested_quantity numeric(12, 4) NOT NULL CHECK (requested_quantity > 0),
    fulfilled_quantity numeric(12, 4) NOT NULL DEFAULT 0 CHECK (fulfilled_quantity >= 0),

    CONSTRAINT fk_order_line_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT uq_order_line_pku UNIQUE (order_id, pku_id),
    CONSTRAINT uq_order_line_id_sku UNIQUE (id, sku_id),
    CONSTRAINT chk_fulfillment_bounds CHECK (fulfilled_quantity <= requested_quantity)
);

CREATE INDEX idx_order_lines_order ON outbound_order_lines (order_id);
CREATE INDEX idx_order_lines_sku ON outbound_order_lines (sku_id);
CREATE INDEX idx_order_lines_pku ON outbound_order_lines (pku_id);

CREATE TABLE inventory_allocations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    order_line_id bigint NOT NULL,
    balance_id bigint NOT NULL,
    sku_id bigint NOT NULL,

    allocated_quantity numeric(12, 4) NOT NULL CHECK (allocated_quantity > 0),
    picked_quantity numeric(12,4) NOT NULL DEFAULT 0 CHECK (picked_quantity >=0),
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_alloc_order_line 
        FOREIGN KEY (order_line_id, sku_id) 
        REFERENCES outbound_order_lines(id, sku_id) 
        ON DELETE CASCADE,

    -- Guarantees the allocation pulls from a balance of the SAME SKU
    CONSTRAINT fk_alloc_balance 
        FOREIGN KEY (balance_id, sku_id) 
        REFERENCES inventory_balances(id, sku_id) 
        ON DELETE RESTRICT,

    CONSTRAINT uq_order_line_balance UNIQUE (order_line_id, balance_id),
    CONSTRAINT chk_picked_le_allocated CHECK (picked_quantity <= allocated_quantity)
);

CREATE INDEX idx_allocations_order_line ON inventory_allocations (order_line_id);
CREATE INDEX idx_allocations_balance ON inventory_allocations (balance_id);

-- ------------------------------------------------------------
-- 5. MOVEMENTS & AUDIT LEDGER
-- ------------------------------------------------------------

CREATE TYPE movement_reason AS ENUM (
    'RECEIVING',
    'PUTAWAY',
    'PICK',
    'REPLENISHMENT',
    'INTERNAL_TRANSFER',
    'BREAK_PACKAGE',
    'REPACKAGE',
    'CYCLE_COUNT',
    'SCRAP_DAMAGED',
    'RETURN'
);

CREATE TABLE inventory_movements (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    lot_id bigint,
    package_count numeric(12, 4) NOT NULL CHECK (package_count >= 0),
    quantity numeric(12, 4) NOT NULL CHECK (quantity > 0),

    source_node_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    destination_node_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,

    reason movement_reason NOT NULL,
    reference_id text COLLATE "C",
    allocation_id bigint 
        REFERENCES inventory_allocations(id) 
        ON DELETE RESTRICT,
    is_sealed boolean NOT NULL DEFAULT true,
    operator_id text COLLATE "C" NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_movement_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT fk_movement_lot 
        FOREIGN KEY (lot_id, sku_id) 
        REFERENCES lots(id, sku_id) 
        ON DELETE RESTRICT,

    CONSTRAINT chk_allocation_only_for_pick CHECK (
        allocation_id IS NULL OR (reason = 'PICK' AND source_node_id IS NOT NULL)
    ),

    CONSTRAINT chk_unsealed_no_packages 
      CHECK (is_sealed OR package_count = 0),

    CONSTRAINT chk_movement_endpoints CHECK (
        source_node_id IS NOT NULL OR destination_node_id IS NOT NULL
    ),
    CONSTRAINT chk_movement_distinct_endpoints CHECK (
        source_node_id IS NULL OR destination_node_id IS NULL OR source_node_id != destination_node_id
    )
);

CREATE INDEX idx_movements_sku ON inventory_movements (sku_id, created_at DESC);
CREATE INDEX idx_movements_pku ON inventory_movements (pku_id, created_at DESC);
CREATE INDEX idx_movements_lot ON inventory_movements (lot_id, created_at DESC);
CREATE INDEX idx_movements_source ON inventory_movements (source_node_id, created_at DESC) WHERE source_node_id IS NOT NULL;
CREATE INDEX idx_movements_dest ON inventory_movements (destination_node_id, created_at DESC) WHERE destination_node_id IS NOT NULL;
CREATE INDEX idx_movements_allocation ON inventory_movements (allocation_id) WHERE allocation_id IS NOT NULL;

-- ------------------------------------------------------------
-- 6. INBOUND PROCUREMENT & TASKS
-- ------------------------------------------------------------

CREATE TYPE inbound_order_status AS ENUM (
    'DRAFT',
    'ISSUED',
    'PARTIALLY_RECEIVED',
    'RECEIVED',
    'CANCELLED'
);

CREATE TABLE inbound_orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    po_number text COLLATE "C" NOT NULL UNIQUE,
    tenant_id bigint,
    vendor_name text NOT NULL,
    version integer NOT NULL DEFAULT 1,
    status inbound_order_status NOT NULL DEFAULT 'ISSUED',
    expected_delivery date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE inbound_order_lines (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inbound_order_id bigint NOT NULL 
        REFERENCES inbound_orders(id) 
        ON DELETE CASCADE,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    expected_quantity numeric(12, 4) NOT NULL CHECK (expected_quantity > 0),
    received_quantity numeric(12, 4) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),

    CONSTRAINT fk_po_line_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT uq_po_line_pku UNIQUE (inbound_order_id, pku_id)
);

CREATE INDEX idx_po_lines_po ON inbound_order_lines (inbound_order_id);
CREATE INDEX idx_po_lines_sku ON inbound_order_lines (sku_id);

CREATE TYPE task_type AS ENUM (
    'PUTAWAY',
    'PICK',
    'REPLENISH',
    'COUNT',
    'RELOCATE_NODE'
);

CREATE TYPE task_status AS ENUM (
    'PENDING',
    'ASSIGNED',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);

CREATE TABLE warehouse_tasks (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    task_type task_type NOT NULL,
    status task_status NOT NULL DEFAULT 'PENDING',
    priority integer NOT NULL DEFAULT 100,

    -- Stock-level directives
    sku_id bigint REFERENCES stock_keeping_units(id) ON DELETE RESTRICT,
    pku_id bigint,
    lot_id bigint,
    package_count numeric(12, 4) CHECK (package_count > 0),
    quantity numeric(12, 4) CHECK (quantity > 0),

    -- Container-level directives (e.g. moving an entire pallet)
    target_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,

    source_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    destination_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,

    order_line_id bigint REFERENCES outbound_order_lines(id) ON DELETE SET NULL,
    allocation_id bigint REFERENCES inventory_allocations(id) ON DELETE SET NULL,

    assigned_operator_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,

    CONSTRAINT fk_task_pku FOREIGN KEY (pku_id, sku_id)
        REFERENCES sku_packaging_units(id, sku_id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_lot FOREIGN KEY (lot_id, sku_id)
        REFERENCES lots(id, sku_id) ON DELETE RESTRICT,
    CONSTRAINT chk_task_sku_present CHECK (
        (pku_id IS NULL AND lot_id IS NULL) OR sku_id IS NOT NULL
    ),
    CONSTRAINT chk_task_payload CHECK (
        target_node_id IS NOT NULL OR (pku_id IS NOT NULL AND quantity IS NOT NULL)
    )
);

CREATE INDEX idx_tasks_execution ON warehouse_tasks (status, priority DESC, created_at ASC);
CREATE INDEX idx_tasks_operator ON warehouse_tasks (assigned_operator_id) WHERE assigned_operator_id IS NOT NULL;

CREATE TABLE node_relocations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    node_id bigint NOT NULL REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    from_parent_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    to_parent_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    from_path ltree NOT NULL,
    to_path ltree NOT NULL,
    operator_id text COLLATE "C" NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_relocations_node ON node_relocations (node_id, created_at DESC);

CREATE TYPE receipt_status AS ENUM (
    'RECEIVING',  -- Worker is currently scanning items on the dock
    'COMPLETED',  -- Truck is gone, inventory is confirmed
    'CANCELLED'
);

CREATE TABLE receipts (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inbound_order_id bigint NOT NULL 
        REFERENCES inbound_orders(id) 
        ON DELETE RESTRICT,
    receipt_number text COLLATE "C" NOT NULL UNIQUE,
    status receipt_status NOT NULL DEFAULT 'RECEIVING',
    operator_id text COLLATE "C" NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE receipt_lines (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    receipt_id bigint NOT NULL 
        REFERENCES receipts(id) 
        ON DELETE CASCADE,
    inbound_order_line_id bigint 
        REFERENCES inbound_order_lines(id) 
        ON DELETE RESTRICT,
    
    -- The actual physical items counted
    sku_id bigint NOT NULL REFERENCES stock_keeping_units(id) ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    lot_id bigint,
    received_quantity numeric(12, 4) NOT NULL CHECK (received_quantity > 0),
    package_count numeric(12, 4) NOT NULL CHECK (package_count >= 0),
    
    -- Maintain strict composites
    CONSTRAINT fk_receipt_line_pku FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) ON DELETE RESTRICT,
    CONSTRAINT fk_receipt_line_lot FOREIGN KEY (lot_id, sku_id) 
        REFERENCES lots(id, sku_id) ON DELETE RESTRICT
);

CREATE INDEX idx_receipt_lines_receipt ON receipt_lines(receipt_id);

CREATE TYPE shipment_status AS ENUM (
    'STAGED',    -- Sitting on the outbound dock
    'SHIPPED',   -- Carrier picked it up
    'DELIVERED', -- Optional: Updated via carrier API webhooks
    'CANCELLED'
);

CREATE TABLE shipments (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shipment_number text COLLATE "C" NOT NULL UNIQUE,
    carrier_name text NOT NULL, -- e.g., 'FedEx', 'UPS', 'Internal Fleet'
    master_tracking_number text COLLATE "C",
    status shipment_status NOT NULL DEFAULT 'STAGED',
    shipped_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Handling Units represent physical boxes, pallets, or totes leaving the building
CREATE TABLE handling_units (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    outbound_order_id bigint NOT NULL 
        REFERENCES outbound_orders(id) 
        ON DELETE RESTRICT,
    shipment_id bigint 
        REFERENCES shipments(id) 
        ON DELETE SET NULL, -- A box is packed before it is assigned to a truck
        
    sscc text COLLATE "C" UNIQUE, -- Standard Serial Shipping Container Code barcode
    tracking_number text COLLATE "C", -- Box-level tracking label
    
    tare_weight_kg numeric(10, 3) DEFAULT 0 CHECK (tare_weight_kg >= 0),
    gross_weight_kg numeric(10, 3) DEFAULT 0 CHECK (gross_weight_kg >= 0),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Maps the internal warehouse allocation to the physical outbound box
CREATE TABLE handling_unit_contents (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    handling_unit_id bigint NOT NULL 
        REFERENCES handling_units(id) 
        ON DELETE CASCADE,
    allocation_id bigint NOT NULL 
        REFERENCES inventory_allocations(id) 
        ON DELETE RESTRICT,
    packed_quantity numeric(12, 4) NOT NULL CHECK (packed_quantity > 0)
);

CREATE INDEX idx_handling_units_order ON handling_units(outbound_order_id);
CREATE INDEX idx_handling_units_shipment ON handling_units(shipment_id);

-- +goose Down
DROP TABLE IF EXISTS handling_unit_contents;
DROP TABLE IF EXISTS handling_units;
DROP TABLE IF EXISTS shipments;
DROP TYPE IF EXISTS  shipment_status;
DROP TABLE IF EXISTS receipt_lines;
DROP TABLE IF EXISTS receipts;
DROP TYPE IF EXISTS receipt_status;

DROP TABLE IF EXISTS node_relocations;
DROP TABLE IF EXISTS warehouse_tasks;
DROP TYPE IF EXISTS task_status;
DROP TYPE IF EXISTS task_type;

DROP TABLE IF EXISTS inbound_order_lines;
DROP TABLE IF EXISTS inbound_orders;
DROP TYPE IF EXISTS inbound_order_status;

DROP TABLE IF EXISTS inventory_movements;
DROP TYPE IF EXISTS movement_reason;

DROP TABLE IF EXISTS inventory_allocations;
DROP TABLE IF EXISTS outbound_order_lines;
DROP TABLE IF EXISTS outbound_orders;
DROP TYPE IF EXISTS order_status;

DROP TABLE IF EXISTS inventory_balances;
DROP TABLE IF EXISTS storage_nodes;
DROP TYPE IF EXISTS storage_node_type;

DROP TABLE IF EXISTS lots;
DROP TYPE IF EXISTS lot_status;
DROP TABLE IF EXISTS sku_packaging_units;
DROP TABLE IF EXISTS stock_keeping_units;
DROP TYPE IF EXISTS uom;

-- +goose StatementBegin
DROP EXTENSION IF EXISTS ltree;
DROP EXTENSION IF EXISTS pg_trgm;
-- +goose StatementEnd
