-- +goose Up

-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS ltree;
-- +goose StatementEnd

-- ------------------------------------------------------------
-- 1. MASTER DATA: SKUS, PACKAGING & LOTS
-- ------------------------------------------------------------

CREATE TYPE uom AS ENUM (
    'EACH',
    'Kg',
    'g',
    'm',
    'L',
    'mL'
);

CREATE TABLE stock_keeping_units (
    id bigint 
        GENERATED ALWAYS AS IDENTITY (START WITH 10000) 
        PRIMARY KEY,
    name text NOT NULL,
    base_uom uom NOT NULL DEFAULT 'EACH',
    is_discrete boolean NOT NULL DEFAULT true,
    requires_lot_tracking boolean NOT NULL DEFAULT false,
    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_skus_name_trgm ON stock_keeping_units USING gin (name gin_trgm_ops);
CREATE INDEX idx_skus_attributes ON stock_keeping_units USING gin (attributes);

CREATE TABLE sku_packaging_units (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sku_id bigint NOT NULL REFERENCES stock_keeping_units(id) ON DELETE CASCADE,
    unit_name text NOT NULL,
    conversion_factor numeric(12, 4) NOT NULL CHECK (conversion_factor > 0),
    parent_packaging_unit_id bigint,
    is_base_unit boolean NOT NULL DEFAULT false,
    allows_break_bulk boolean NOT NULL DEFAULT false,
    barcode text COLLATE "C" UNIQUE,
    tare_weight_kg numeric(10, 3) CHECK (tare_weight_kg >= 0),
    gross_volume_cm3 numeric(12, 2) CHECK (gross_volume_cm3 > 0),

    CONSTRAINT uq_sku_unit_name UNIQUE (sku_id, unit_name),
    CONSTRAINT uq_sku_packaging_units_id_sku UNIQUE (id, sku_id),

    CONSTRAINT chk_base_unit_factor CHECK (
        NOT is_base_unit OR conversion_factor = 1.0000
    ),
    CONSTRAINT fk_pku_same_sku_parent 
        FOREIGN KEY (parent_packaging_unit_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT chk_base_unit_no_parent CHECK (
        NOT is_base_unit OR parent_packaging_unit_id IS NULL
    ),
    CONSTRAINT chk_no_self_parent CHECK (
        parent_packaging_unit_id IS NULL OR parent_packaging_unit_id != id
    )
);

CREATE UNIQUE INDEX uq_sku_single_base_unit 
    ON sku_packaging_units (sku_id) 
    WHERE is_base_unit = true;

CREATE INDEX idx_packaging_units_sku ON sku_packaging_units (sku_id);

CREATE TYPE lot_status AS ENUM (
    'AVAILABLE',
    'QUARANTINED',
    'EXPIRED',
    'RECALLED'
);

CREATE TABLE lots (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    lot_number text COLLATE "C" NOT NULL,
    status lot_status NOT NULL DEFAULT 'AVAILABLE',
    manufactured_at date,
    expires_at date,
    received_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_sku_lot_number UNIQUE (sku_id, lot_number),
    CONSTRAINT uq_sku_lot_id UNIQUE (id, sku_id)
);

CREATE INDEX idx_lots_expiration ON lots (expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_lots_status ON lots (status);

-- ------------------------------------------------------------
-- 2. UNIFIED STORAGE HIERARCHY (BINS, PALLETS & TOTES)
-- ------------------------------------------------------------

CREATE TYPE storage_node_type AS ENUM (
    'WAREHOUSE',
    'ZONE',
    'AISLE',
    'BAY',
    'BIN',       -- Immobile physical locations
    'PALLET',
    'TOTE',
    'CART'       -- Mobile handling units
);

CREATE TABLE storage_nodes (
    id bigint 
        GENERATED BY DEFAULT AS IDENTITY 
        PRIMARY KEY,
    parent_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    path ltree NOT NULL,
    code text COLLATE "C" NOT NULL UNIQUE,
    node_type storage_node_type NOT NULL DEFAULT 'BIN',
    is_movable boolean NOT NULL DEFAULT false,
    max_weight_kg numeric(10, 2) CHECK (max_weight_kg > 0),
    max_volume_cm3 numeric(12, 2) CHECK (max_volume_cm3 > 0),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_storage_nodes_path_gist ON storage_nodes USING gist (path);
CREATE INDEX idx_storage_nodes_path_btree ON storage_nodes (path);
CREATE INDEX idx_storage_nodes_parent_id ON storage_nodes (parent_id);
CREATE INDEX idx_storage_nodes_type ON storage_nodes (node_type);

-- ------------------------------------------------------------
-- 3. INVENTORY BALANCES
-- ------------------------------------------------------------

CREATE TABLE inventory_balances (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    node_id bigint NOT NULL 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    lot_id bigint,

    is_sealed boolean NOT NULL DEFAULT true,
    package_count numeric(12, 4) NOT NULL CHECK (package_count >= 0),

    -- Quantities always stored in the SKU's atomic base UOM
    on_hand numeric(12, 4) NOT NULL DEFAULT 0,
    allocated numeric(12, 4) NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_on_hand_positive CHECK (on_hand >= 0),
    CONSTRAINT chk_allocated_positive CHECK (allocated >= 0),
    CONSTRAINT chk_allocated_le_on_hand CHECK (allocated <= on_hand),
    CONSTRAINT chk_unsealed_no_packages 
      CHECK (is_sealed OR package_count = 0),

    -- Composite foreign keys prevent cross-SKU lot/PKU mixing
    CONSTRAINT fk_balance_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT fk_balance_lot 
        FOREIGN KEY (lot_id, sku_id) 
        REFERENCES lots(id, sku_id) 
        ON DELETE RESTRICT
);

ALTER TABLE inventory_balances SET (fillfactor = 70);

-- Unique entry per Node + PKU + Lot + Sealed State
CREATE UNIQUE INDEX uq_node_inventory 
    ON inventory_balances (node_id, pku_id, lot_id, is_sealed) NULLS NOT DISTINCT;

CREATE INDEX idx_balances_reservable 
    ON inventory_balances (sku_id, pku_id, is_sealed, lot_id);

CREATE INDEX idx_balances_node ON inventory_balances (node_id);

-- ------------------------------------------------------------
-- 4. OUTBOUND DEMAND & ALLOCATION ENGINE
-- ------------------------------------------------------------

CREATE TYPE order_status AS ENUM (
    'PENDING',
    'ALLOCATED',
    'PARTIALLY_ALLOCATED',
    'PICKING',
    'PACKED',
    'SHIPPED',
    'CANCELLED'
);

CREATE TABLE outbound_orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_number text COLLATE "C" NOT NULL UNIQUE,
    customer_name text,
    status order_status NOT NULL DEFAULT 'PENDING',
    priority integer NOT NULL DEFAULT 100,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_status_priority 
    ON outbound_orders (status, priority DESC, created_at ASC);

CREATE TABLE outbound_order_lines (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL 
        REFERENCES outbound_orders(id) 
        ON DELETE CASCADE,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    requested_quantity numeric(12, 4) NOT NULL CHECK (requested_quantity > 0),
    fulfilled_quantity numeric(12, 4) NOT NULL DEFAULT 0 CHECK (fulfilled_quantity >= 0),

    CONSTRAINT fk_order_line_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT uq_order_line_pku UNIQUE (order_id, pku_id),
    CONSTRAINT chk_fulfillment_bounds CHECK (fulfilled_quantity <= requested_quantity)
);

CREATE INDEX idx_order_lines_order ON outbound_order_lines (order_id);
CREATE INDEX idx_order_lines_sku ON outbound_order_lines (sku_id);
CREATE INDEX idx_order_lines_pku ON outbound_order_lines (pku_id);

CREATE TABLE inventory_allocations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    order_line_id bigint NOT NULL 
        REFERENCES outbound_order_lines(id) 
        ON DELETE CASCADE,
    balance_id bigint NOT NULL 
        REFERENCES inventory_balances(id) 
        ON DELETE RESTRICT,
    allocated_quantity numeric(12, 4) NOT NULL CHECK (allocated_quantity > 0),
    picked_quantity numeric(12,4) NOT NULL DEFAULT 0 CHECK (picked_quantity >=0),
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_alloc_order_line 
        FOREIGN KEY (order_line_id, sku_id) 
        REFERENCES outbound_order_lines(id, sku_id) 
        ON DELETE CASCADE,

    -- Guarantees the allocation pulls from a balance of the SAME SKU
    CONSTRAINT fk_alloc_balance 
        FOREIGN KEY (balance_id, sku_id) 
        REFERENCES inventory_balances(id, sku_id) 
        ON DELETE RESTRICT,

    CONSTRAINT uq_order_line_balance UNIQUE (order_line_id, balance_id),
    CONSTRAINT chk_picked_le_allocated CHECK (picked_quantity <= allocated_quantity)
);

CREATE INDEX idx_allocations_order_line ON inventory_allocations (order_line_id);
CREATE INDEX idx_allocations_balance ON inventory_allocations (balance_id);

-- ------------------------------------------------------------
-- 5. MOVEMENTS & AUDIT LEDGER
-- ------------------------------------------------------------

CREATE TYPE movement_reason AS ENUM (
    'RECEIVING',
    'PUTAWAY',
    'PICK',
    'REPLENISHMENT',
    'INTERNAL_TRANSFER',
    'BREAK_PACKAGE',
    'REPACKAGE',
    'CYCLE_COUNT',
    'SCRAP_DAMAGED',
    'RETURN'
);

CREATE TABLE inventory_movements (
    id bigint 
        GENERATED ALWAYS AS IDENTITY 
        PRIMARY KEY,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    lot_id bigint,
    package_count numeric(12, 4) NOT NULL CHECK (package_count >= 0),
    quantity numeric(12, 4) NOT NULL CHECK (quantity > 0),

    source_node_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,
    destination_node_id bigint 
        REFERENCES storage_nodes(id) 
        ON DELETE RESTRICT,

    reason movement_reason NOT NULL,
    reference_id text COLLATE "C",
    allocation_id bigint 
        REFERENCES inventory_allocations(id) 
        ON DELETE RESTRICT,
    is_sealed boolean NOT NULL DEFAULT true,
    operator_id text COLLATE "C" NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_movement_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT fk_movement_lot 
        FOREIGN KEY (lot_id, sku_id) 
        REFERENCES lots(id, sku_id) 
        ON DELETE RESTRICT,

    CONSTRAINT chk_allocation_only_for_pick CHECK (
        allocation_id IS NULL OR (reason = 'PICK' AND source_node_id IS NOT NULL)
    ),

    CONSTRAINT chk_unsealed_no_packages 
      CHECK (is_sealed OR package_count = 0),

    CONSTRAINT chk_movement_endpoints CHECK (
        source_node_id IS NOT NULL OR destination_node_id IS NOT NULL
    ),
    CONSTRAINT chk_movement_distinct_endpoints CHECK (
        source_node_id IS NULL OR destination_node_id IS NULL OR source_node_id != destination_node_id
    )
);

CREATE INDEX idx_movements_sku ON inventory_movements (sku_id, created_at DESC);
CREATE INDEX idx_movements_pku ON inventory_movements (pku_id, created_at DESC);
CREATE INDEX idx_movements_lot ON inventory_movements (lot_id, created_at DESC);
CREATE INDEX idx_movements_source ON inventory_movements (source_node_id, created_at DESC) WHERE source_node_id IS NOT NULL;
CREATE INDEX idx_movements_dest ON inventory_movements (destination_node_id, created_at DESC) WHERE destination_node_id IS NOT NULL;
CREATE INDEX idx_movements_allocation ON inventory_movements (allocation_id) WHERE allocation_id IS NOT NULL;

-- ------------------------------------------------------------
-- 6. INBOUND PROCUREMENT & TASKS
-- ------------------------------------------------------------

CREATE TYPE inbound_order_status AS ENUM (
    'DRAFT',
    'ISSUED',
    'PARTIALLY_RECEIVED',
    'RECEIVED',
    'CANCELLED'
);

CREATE TABLE inbound_orders (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    po_number text COLLATE "C" NOT NULL UNIQUE,
    vendor_name text NOT NULL,
    status inbound_order_status NOT NULL DEFAULT 'ISSUED',
    expected_delivery date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE inbound_order_lines (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    inbound_order_id bigint NOT NULL 
        REFERENCES inbound_orders(id) 
        ON DELETE CASCADE,
    sku_id bigint NOT NULL 
        REFERENCES stock_keeping_units(id) 
        ON DELETE RESTRICT,
    pku_id bigint NOT NULL,
    expected_quantity numeric(12, 4) NOT NULL CHECK (expected_quantity > 0),
    received_quantity numeric(12, 4) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),

    CONSTRAINT fk_po_line_pku 
        FOREIGN KEY (pku_id, sku_id) 
        REFERENCES sku_packaging_units(id, sku_id) 
        ON DELETE RESTRICT,
    CONSTRAINT uq_po_line_pku UNIQUE (inbound_order_id, pku_id)
);

CREATE INDEX idx_po_lines_po ON inbound_order_lines (inbound_order_id);
CREATE INDEX idx_po_lines_sku ON inbound_order_lines (sku_id);

CREATE TYPE task_type AS ENUM (
    'PUTAWAY',
    'PICK',
    'REPLENISH',
    'COUNT',
    'RELOCATE_NODE'
);

CREATE TYPE task_status AS ENUM (
    'PENDING',
    'ASSIGNED',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);

CREATE TABLE warehouse_tasks (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    task_type task_type NOT NULL,
    status task_status NOT NULL DEFAULT 'PENDING',
    priority integer NOT NULL DEFAULT 100,

    -- Stock-level directives
    sku_id bigint REFERENCES stock_keeping_units(id) ON DELETE RESTRICT,
    pku_id bigint,
    lot_id bigint,
    package_count numeric(12, 4) CHECK (package_count > 0),
    quantity numeric(12, 4) CHECK (quantity > 0),

    -- Container-level directives (e.g. moving an entire pallet)
    target_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,

    source_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    destination_node_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,

    order_line_id bigint REFERENCES outbound_order_lines(id) ON DELETE SET NULL,
    allocation_id bigint REFERENCES inventory_allocations(id) ON DELETE SET NULL,

    assigned_operator_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,

    CONSTRAINT fk_task_pku FOREIGN KEY (pku_id, sku_id)
        REFERENCES sku_packaging_units(id, sku_id) ON DELETE RESTRICT,
    CONSTRAINT fk_task_lot FOREIGN KEY (lot_id, sku_id)
        REFERENCES lots(id, sku_id) ON DELETE RESTRICT,
    CONSTRAINT chk_task_sku_present CHECK (
        (pku_id IS NULL AND lot_id IS NULL) OR sku_id IS NOT NULL
    ),
    CONSTRAINT chk_task_payload CHECK (
        target_node_id IS NOT NULL OR (pku_id IS NOT NULL AND quantity IS NOT NULL)
    )
);

CREATE INDEX idx_tasks_execution ON warehouse_tasks (status, priority DESC, created_at ASC);
CREATE INDEX idx_tasks_operator ON warehouse_tasks (assigned_operator_id) WHERE assigned_operator_id IS NOT NULL;

CREATE TABLE node_relocations (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    node_id bigint NOT NULL REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    from_parent_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    to_parent_id bigint REFERENCES storage_nodes(id) ON DELETE RESTRICT,
    from_path ltree NOT NULL,
    to_path ltree NOT NULL,
    operator_id text COLLATE "C" NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_relocations_node ON node_relocations (node_id, created_at DESC);

-- ------------------------------------------------------------
-- 7. ESSENTIAL DATABASE INTEGRITY TRIGGERS
-- ------------------------------------------------------------

-- A. Maintain storage_node ltree path on creation
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_storage_node_path()
RETURNS TRIGGER AS $func$
DECLARE
    parent_path ltree;
BEGIN
    IF NEW.parent_id IS NULL THEN
        NEW.path := text2ltree(NEW.id::text);
        RETURN NEW;
    END IF;

    SELECT path INTO parent_path 
    FROM storage_nodes 
    WHERE id = NEW.parent_id;

    IF parent_path IS NULL THEN
        RAISE EXCEPTION 'Parent storage node ID % does not exist', NEW.parent_id;
    END IF;

    NEW.path := parent_path || text2ltree(NEW.id::text);
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_set_storage_node_path
BEFORE INSERT ON storage_nodes
FOR EACH ROW
EXECUTE FUNCTION set_storage_node_path();

-- B. Recompute path and guard against cycles when reparenting
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION update_storage_node_parent_change()
RETURNS TRIGGER AS $func$
DECLARE
    parent_path ltree;
BEGIN
    IF NEW.parent_id IS NULL THEN
        NEW.path := text2ltree(NEW.id::text);
        RETURN NEW;
    END IF;

    IF NEW.parent_id = NEW.id THEN
        RAISE EXCEPTION 'Storage node % cannot be its own parent', NEW.id;
    END IF;

    SELECT path INTO parent_path 
    FROM storage_nodes 
    WHERE id = NEW.parent_id;

    IF parent_path IS NULL THEN
        RAISE EXCEPTION 'Parent storage node ID % does not exist', NEW.parent_id;
    END IF;

    -- Cycle check: parent cannot be inside this node's own subtree
    IF parent_path <@ OLD.path THEN
        RAISE EXCEPTION 'Cyclic hierarchy detected: Node % cannot be moved into its descendant branch (Node %)',
            NEW.id, NEW.parent_id;
    END IF;

    NEW.path := parent_path || text2ltree(NEW.id::text);
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_update_storage_node_parent_change
BEFORE UPDATE OF parent_id ON storage_nodes
FOR EACH ROW
WHEN (OLD.parent_id IS DISTINCT FROM NEW.parent_id)
EXECUTE FUNCTION update_storage_node_parent_change();

-- C. Cascade path updates down to all descendants
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION update_storage_node_subtree_path()
RETURNS TRIGGER AS $func$
BEGIN
    IF pg_trigger_depth() > 1 THEN
        RETURN NEW;
    END IF;

    UPDATE storage_nodes
    SET path = NEW.path || subpath(path, nlevel(OLD.path))
    WHERE path <@ OLD.path AND id != OLD.id;

    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_update_storage_node_subtree_path
AFTER UPDATE OF path ON storage_nodes
FOR EACH ROW
WHEN (OLD.path IS DISTINCT FROM NEW.path)
EXECUTE FUNCTION update_storage_node_subtree_path();

-- D. Audit Immutability Trigger
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION prevent_movement_mutation()
RETURNS TRIGGER AS $func$
BEGIN
    RAISE EXCEPTION 'Audit violation: % is append-only and cannot be updated or deleted.', TG_TABLE_NAME;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_protect_inventory_movements
BEFORE UPDATE OR DELETE ON inventory_movements
FOR EACH ROW
EXECUTE FUNCTION prevent_movement_mutation();

CREATE TRIGGER trg_protect_inventory_movements_truncate
BEFORE TRUNCATE ON inventory_movements
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_movement_mutation();

-- E. inventory_movemnt to balance trigger 

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION apply_inventory_movement()
RETURNS TRIGGER AS $func$
DECLARE
    v_factor      numeric(12,4);
    v_leg         record;
    v_node        record;
    v_balance_id  bigint;
    v_release     numeric(12,4);
    v_line_id     bigint;
    v_line_factor numeric(12,4);
BEGIN
    SELECT conversion_factor INTO STRICT v_factor
    FROM sku_packaging_units WHERE id = NEW.pku_id;

    IF NEW.is_sealed AND NEW.quantity <> NEW.package_count * v_factor THEN
        RAISE EXCEPTION 'Movement quantity % != package_count % * factor %',
            NEW.quantity, NEW.package_count, v_factor;
    END IF;

    PERFORM set_config('wms.ledger_write', 'on', true);

    FOR v_leg IN
        SELECT node_id, delta_sign
        FROM (VALUES (NEW.source_node_id, -1),
                     (NEW.destination_node_id, 1)) AS t(node_id, delta_sign)
        WHERE node_id IS NOT NULL
        ORDER BY node_id
    LOOP
        -- #6: node must be able to hold stock
        SELECT node_type, is_active INTO STRICT v_node
        FROM storage_nodes WHERE id = v_leg.node_id
        FOR SHARE;

        IF v_node.node_type NOT IN ('BIN', 'PALLET', 'TOTE', 'CART') THEN
            RAISE EXCEPTION 'Node % is a % and cannot hold stock',
                v_leg.node_id, v_node.node_type;
        END IF;

        -- Inactive nodes may be emptied (source) but not filled (destination)
        IF v_leg.delta_sign = 1 AND NOT v_node.is_active THEN
            RAISE EXCEPTION 'Destination node % is inactive', v_leg.node_id;
        END IF;

        IF v_leg.delta_sign = 1 THEN
            INSERT INTO inventory_balances AS ib
                (node_id, sku_id, pku_id, lot_id, is_sealed, package_count, on_hand)
            VALUES
                (v_leg.node_id, NEW.sku_id, NEW.pku_id, NEW.lot_id,
                 NEW.is_sealed, NEW.package_count, NEW.quantity)
            ON CONFLICT (node_id, pku_id, lot_id, is_sealed)
            DO UPDATE SET
                on_hand       = ib.on_hand + EXCLUDED.on_hand,
                package_count = ib.package_count + EXCLUDED.package_count,
                updated_at    = now();
        ELSE
            v_release := CASE WHEN NEW.allocation_id IS NOT NULL
                              THEN NEW.quantity ELSE 0 END;

            UPDATE inventory_balances
            SET on_hand       = on_hand - NEW.quantity,
                package_count = package_count - NEW.package_count,
                allocated     = allocated - v_release,
                updated_at    = now()
            WHERE node_id = v_leg.node_id
              AND pku_id = NEW.pku_id
              AND is_sealed = NEW.is_sealed
              AND lot_id IS NOT DISTINCT FROM NEW.lot_id
            RETURNING id INTO v_balance_id;

            IF NOT FOUND THEN
                RAISE EXCEPTION 'No balance at node % for pku % lot % sealed=%',
                    v_leg.node_id, NEW.pku_id, NEW.lot_id, NEW.is_sealed;
            END IF;

            -- #2: consume the allocation and advance the order line
            IF NEW.allocation_id IS NOT NULL THEN
                UPDATE inventory_allocations
                SET picked_quantity = picked_quantity + NEW.quantity
                WHERE id = NEW.allocation_id
                  AND balance_id = v_balance_id
                RETURNING order_line_id INTO v_line_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Allocation % does not belong to the source balance',
                        NEW.allocation_id;
                END IF;

                -- Line quantities are in the line's PKU; movement quantity is base UOM
                SELECT pu.conversion_factor INTO STRICT v_line_factor
                FROM outbound_order_lines l
                JOIN sku_packaging_units pu ON pu.id = l.pku_id
                WHERE l.id = v_line_id;

                UPDATE outbound_order_lines
                SET fulfilled_quantity = fulfilled_quantity + NEW.quantity / v_line_factor
                WHERE id = v_line_id;
            END IF;
        END IF;
    END LOOP;

    PERFORM set_config('wms.ledger_write', 'off', true);
    RETURN NULL;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_apply_inventory_movement
AFTER INSERT ON inventory_movements
FOR EACH ROW
EXECUTE FUNCTION apply_inventory_movement();

-- F. Immutability guards
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION guard_balance_ledger_columns()
RETURNS TRIGGER AS $func$
BEGIN
    IF current_setting('wms.ledger_write', true) IS DISTINCT FROM 'on' THEN
        RAISE EXCEPTION 'on_hand/package_count may only change via inventory_movements';
    END IF;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_guard_balance_ins BEFORE INSERT ON inventory_balances
FOR EACH ROW EXECUTE FUNCTION guard_balance_ledger_columns();

CREATE TRIGGER trg_guard_balance_upd BEFORE UPDATE ON inventory_balances
FOR EACH ROW
WHEN (OLD.on_hand IS DISTINCT FROM NEW.on_hand
   OR OLD.package_count IS DISTINCT FROM NEW.package_count)
EXECUTE FUNCTION guard_balance_ledger_columns();

CREATE TRIGGER trg_guard_balance_del BEFORE DELETE ON inventory_balances
FOR EACH ROW WHEN (OLD.on_hand <> 0)
EXECUTE FUNCTION guard_balance_ledger_columns();

-- G. node relocation

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION log_node_relocation()
RETURNS TRIGGER AS $func$
BEGIN
    INSERT INTO node_relocations
        (node_id, from_parent_id, to_parent_id, from_path, to_path, operator_id)
    VALUES
        (NEW.id, OLD.parent_id, NEW.parent_id, OLD.path, NEW.path,
         COALESCE(NULLIF(current_setting('wms.operator_id', true), ''), session_user));
    RETURN NULL;
END;
$func$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- Fires only on the moved node; descendants change path, not parent_id
CREATE TRIGGER trg_log_node_relocation
AFTER UPDATE OF parent_id ON storage_nodes
FOR EACH ROW
WHEN (OLD.parent_id IS DISTINCT FROM NEW.parent_id)
EXECUTE FUNCTION log_node_relocation();

CREATE TRIGGER trg_protect_node_relocations
BEFORE UPDATE OR DELETE ON node_relocations
FOR EACH ROW EXECUTE FUNCTION prevent_movement_mutation();

CREATE TRIGGER trg_protect_node_relocations_truncate
BEFORE TRUNCATE ON node_relocations
FOR EACH STATEMENT EXECUTE FUNCTION prevent_movement_mutation();

-- +goose Down
DROP TRIGGER IF EXISTS trg_protect_node_relocations_truncate ON node_relocations;
DROP TRIGGER IF EXISTS trg_protect_node_relocations ON node_relocations;
DROP TRIGGER IF EXISTS trg_log_node_relocation ON storage_nodes;
DROP FUNCTION IF EXISTS log_node_relocation();

DROP TRIGGER IF EXISTS trg_guard_balance_del ON inventory_balances;
DROP TRIGGER IF EXISTS trg_guard_balance_upd ON inventory_balances;
DROP TRIGGER IF EXISTS trg_guard_balance_ins ON inventory_balances;
DROP FUNCTION IF EXISTS guard_balance_ledger_columns();

DROP TRIGGER IF EXISTS trg_apply_inventory_movement ON inventory_movements;
DROP FUNCTION IF EXISTS apply_inventory_movement();

DROP TRIGGER IF EXISTS trg_protect_inventory_movements_truncate ON inventory_movements;
DROP TRIGGER IF EXISTS trg_protect_inventory_movements ON inventory_movements;
DROP FUNCTION IF EXISTS prevent_movement_mutation();

DROP TRIGGER IF EXISTS trg_update_storage_node_subtree_path ON storage_nodes;
DROP FUNCTION IF EXISTS update_storage_node_subtree_path();

DROP TRIGGER IF EXISTS trg_update_storage_node_parent_change ON storage_nodes;
DROP FUNCTION IF EXISTS update_storage_node_parent_change();

DROP TRIGGER IF EXISTS trg_set_storage_node_path ON storage_nodes;
DROP FUNCTION IF EXISTS set_storage_node_path();

DROP TABLE IF EXISTS node_relocations;
DROP TABLE IF EXISTS warehouse_tasks;
DROP TYPE IF EXISTS task_status;
DROP TYPE IF EXISTS task_type;

DROP TABLE IF EXISTS inbound_order_lines;
DROP TABLE IF EXISTS inbound_orders;
DROP TYPE IF EXISTS inbound_order_status;

DROP TABLE IF EXISTS inventory_movements;
DROP TYPE IF EXISTS movement_reason;

DROP TABLE IF EXISTS inventory_allocations;
DROP TABLE IF EXISTS outbound_order_lines;
DROP TABLE IF EXISTS outbound_orders;
DROP TYPE IF EXISTS order_status;

DROP TABLE IF EXISTS inventory_balances;
DROP TABLE IF EXISTS storage_nodes;
DROP TYPE IF EXISTS storage_node_type;

DROP TABLE IF EXISTS lots;
DROP TYPE IF EXISTS lot_status;
DROP TABLE IF EXISTS sku_packaging_units;
DROP TABLE IF EXISTS stock_keeping_units;
DROP TYPE IF EXISTS uom;

-- +goose StatementBegin
DROP EXTENSION IF EXISTS ltree;
DROP EXTENSION IF EXISTS pg_trgm;
-- +goose StatementEnd
