// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbound_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInboundOrder = `-- name: CreateInboundOrder :one
INSERT INTO inbound_orders (
    po_number,
    vendor_name,
    status,
    expected_delivery
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, po_number, vendor_name, status, expected_delivery, created_at, updated_at
`

type CreateInboundOrderParams struct {
	PoNumber         string
	VendorName       string
	Status           InboundOrderStatus
	ExpectedDelivery pgtype.Date
}

func (q *Queries) CreateInboundOrder(ctx context.Context, arg CreateInboundOrderParams) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, createInboundOrder,
		arg.PoNumber,
		arg.VendorName,
		arg.Status,
		arg.ExpectedDelivery,
	)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.VendorName,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInboundOrderLine = `-- name: CreateInboundOrderLine :one
INSERT INTO inbound_order_lines (
    inbound_order_id,
    sku_id,
    pku_id,
    expected_quantity,
    received_quantity
) VALUES (
    $1, $2, $3, $4, 0
)
RETURNING id, inbound_order_id, sku_id, pku_id, expected_quantity, received_quantity
`

type CreateInboundOrderLineParams struct {
	InboundOrderID   int64
	SkuID            int64
	PkuID            int64
	ExpectedQuantity pgtype.Numeric
}

func (q *Queries) CreateInboundOrderLine(ctx context.Context, arg CreateInboundOrderLineParams) (InboundOrderLine, error) {
	row := q.db.QueryRow(ctx, createInboundOrderLine,
		arg.InboundOrderID,
		arg.SkuID,
		arg.PkuID,
		arg.ExpectedQuantity,
	)
	var i InboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.InboundOrderID,
		&i.SkuID,
		&i.PkuID,
		&i.ExpectedQuantity,
		&i.ReceivedQuantity,
	)
	return i, err
}

const deleteInboundOrder = `-- name: DeleteInboundOrder :execrows
DELETE FROM inbound_orders
WHERE id = $1
`

func (q *Queries) DeleteInboundOrder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInboundOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInboundOrderByID = `-- name: GetInboundOrderByID :one
SELECT id, po_number, vendor_name, status, expected_delivery, created_at, updated_at FROM inbound_orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInboundOrderByID(ctx context.Context, id int64) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, getInboundOrderByID, id)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.VendorName,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboundOrderByPONumber = `-- name: GetInboundOrderByPONumber :one
SELECT id, po_number, vendor_name, status, expected_delivery, created_at, updated_at FROM inbound_orders
WHERE po_number = $1 LIMIT 1
`

func (q *Queries) GetInboundOrderByPONumber(ctx context.Context, poNumber string) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, getInboundOrderByPONumber, poNumber)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.VendorName,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboundOrderLines = `-- name: GetInboundOrderLines :many
SELECT il.id, il.inbound_order_id, il.sku_id, il.pku_id, il.expected_quantity, il.received_quantity, s.id, s.name AS sku_name, p.unit_name
FROM inbound_order_lines il
JOIN stock_keeping_units s ON il.sku_id = s.id
JOIN sku_packaging_units p ON il.pku_id = p.id
WHERE il.inbound_order_id = $1
`

type GetInboundOrderLinesRow struct {
	ID               int64
	InboundOrderID   int64
	SkuID            int64
	PkuID            int64
	ExpectedQuantity pgtype.Numeric
	ReceivedQuantity pgtype.Numeric
	ID_2             int64
	SkuName          string
	UnitName         string
}

func (q *Queries) GetInboundOrderLines(ctx context.Context, inboundOrderID int64) ([]GetInboundOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, getInboundOrderLines, inboundOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInboundOrderLinesRow
	for rows.Next() {
		var i GetInboundOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.InboundOrderID,
			&i.SkuID,
			&i.PkuID,
			&i.ExpectedQuantity,
			&i.ReceivedQuantity,
			&i.ID_2,
			&i.SkuName,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementInboundLineReceived = `-- name: IncrementInboundLineReceived :one
UPDATE inbound_order_lines
SET received_quantity = received_quantity + $2
WHERE id = $1
RETURNING id, inbound_order_id, sku_id, pku_id, expected_quantity, received_quantity
`

type IncrementInboundLineReceivedParams struct {
	ID               int64
	ReceivedQuantity pgtype.Numeric
}

func (q *Queries) IncrementInboundLineReceived(ctx context.Context, arg IncrementInboundLineReceivedParams) (InboundOrderLine, error) {
	row := q.db.QueryRow(ctx, incrementInboundLineReceived, arg.ID, arg.ReceivedQuantity)
	var i InboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.InboundOrderID,
		&i.SkuID,
		&i.PkuID,
		&i.ExpectedQuantity,
		&i.ReceivedQuantity,
	)
	return i, err
}

const updateInboundOrderStatus = `-- name: UpdateInboundOrderStatus :one
UPDATE inbound_orders
SET
    status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, po_number, vendor_name, status, expected_delivery, created_at, updated_at
`

type UpdateInboundOrderStatusParams struct {
	ID     int64
	Status InboundOrderStatus
}

func (q *Queries) UpdateInboundOrderStatus(ctx context.Context, arg UpdateInboundOrderStatusParams) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, updateInboundOrderStatus, arg.ID, arg.Status)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.VendorName,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
