// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inbound_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInboundOrder = `-- name: CreateInboundOrder :one
INSERT INTO inbound_orders (
    po_number,
    vendor_name,
    status,
    expected_delivery
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, po_number, tenant_id, vendor_name, version, status, expected_delivery, created_at, updated_at
`

type CreateInboundOrderParams struct {
	PoNumber         string
	VendorName       string
	Status           InboundOrderStatus
	ExpectedDelivery pgtype.Date
}

func (q *Queries) CreateInboundOrder(ctx context.Context, arg CreateInboundOrderParams) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, createInboundOrder,
		arg.PoNumber,
		arg.VendorName,
		arg.Status,
		arg.ExpectedDelivery,
	)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.TenantID,
		&i.VendorName,
		&i.Version,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInboundOrderLine = `-- name: CreateInboundOrderLine :one
INSERT INTO inbound_order_lines (
    inbound_order_id,
    sku_id,
    pku_id,
    expected_quantity,
    received_quantity
) VALUES (
    $1, $2, $3, $4, 0
)
RETURNING id, inbound_order_id, sku_id, pku_id, expected_quantity, received_quantity
`

type CreateInboundOrderLineParams struct {
	InboundOrderID   int64
	SkuID            int64
	PkuID            int64
	ExpectedQuantity pgtype.Numeric
}

func (q *Queries) CreateInboundOrderLine(ctx context.Context, arg CreateInboundOrderLineParams) (InboundOrderLine, error) {
	row := q.db.QueryRow(ctx, createInboundOrderLine,
		arg.InboundOrderID,
		arg.SkuID,
		arg.PkuID,
		arg.ExpectedQuantity,
	)
	var i InboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.InboundOrderID,
		&i.SkuID,
		&i.PkuID,
		&i.ExpectedQuantity,
		&i.ReceivedQuantity,
	)
	return i, err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (
    inbound_order_id,
    receipt_number,
    status,
    operator_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, inbound_order_id, receipt_number, status, operator_id, received_at
`

type CreateReceiptParams struct {
	InboundOrderID int64
	ReceiptNumber  string
	Status         ReceiptStatus
	OperatorID     string
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt,
		arg.InboundOrderID,
		arg.ReceiptNumber,
		arg.Status,
		arg.OperatorID,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.InboundOrderID,
		&i.ReceiptNumber,
		&i.Status,
		&i.OperatorID,
		&i.ReceivedAt,
	)
	return i, err
}

const createReceiptLine = `-- name: CreateReceiptLine :one
INSERT INTO receipt_lines (
    receipt_id,
    inbound_order_line_id,
    sku_id,
    pku_id,
    lot_id,
    received_quantity,
    package_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, receipt_id, inbound_order_line_id, sku_id, pku_id, lot_id, received_quantity, package_count
`

type CreateReceiptLineParams struct {
	ReceiptID          int64
	InboundOrderLineID pgtype.Int8
	SkuID              int64
	PkuID              int64
	LotID              pgtype.Int8
	ReceivedQuantity   pgtype.Numeric
	PackageCount       pgtype.Numeric
}

func (q *Queries) CreateReceiptLine(ctx context.Context, arg CreateReceiptLineParams) (ReceiptLine, error) {
	row := q.db.QueryRow(ctx, createReceiptLine,
		arg.ReceiptID,
		arg.InboundOrderLineID,
		arg.SkuID,
		arg.PkuID,
		arg.LotID,
		arg.ReceivedQuantity,
		arg.PackageCount,
	)
	var i ReceiptLine
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.InboundOrderLineID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.ReceivedQuantity,
		&i.PackageCount,
	)
	return i, err
}

const deleteInboundOrder = `-- name: DeleteInboundOrder :execrows
DELETE FROM inbound_orders
WHERE id = $1
`

func (q *Queries) DeleteInboundOrder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInboundOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInboundOrderByID = `-- name: GetInboundOrderByID :one
SELECT id, po_number, tenant_id, vendor_name, version, status, expected_delivery, created_at, updated_at FROM inbound_orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInboundOrderByID(ctx context.Context, id int64) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, getInboundOrderByID, id)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.TenantID,
		&i.VendorName,
		&i.Version,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboundOrderByPONumber = `-- name: GetInboundOrderByPONumber :one
SELECT id, po_number, tenant_id, vendor_name, version, status, expected_delivery, created_at, updated_at FROM inbound_orders
WHERE po_number = $1 LIMIT 1
`

func (q *Queries) GetInboundOrderByPONumber(ctx context.Context, poNumber string) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, getInboundOrderByPONumber, poNumber)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.TenantID,
		&i.VendorName,
		&i.Version,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboundOrderLines = `-- name: GetInboundOrderLines :many
SELECT il.id, il.inbound_order_id, il.sku_id, il.pku_id, il.expected_quantity, il.received_quantity, s.id AS sku_uuid, s.name AS sku_name, p.unit_name
FROM inbound_order_lines il
JOIN stock_keeping_units s ON il.sku_id = s.id
JOIN sku_packaging_units p ON il.pku_id = p.id
WHERE il.inbound_order_id = $1
`

type GetInboundOrderLinesRow struct {
	ID               int64
	InboundOrderID   int64
	SkuID            int64
	PkuID            int64
	ExpectedQuantity pgtype.Numeric
	ReceivedQuantity pgtype.Numeric
	SkuUuid          int64
	SkuName          string
	UnitName         string
}

func (q *Queries) GetInboundOrderLines(ctx context.Context, inboundOrderID int64) ([]GetInboundOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, getInboundOrderLines, inboundOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInboundOrderLinesRow
	for rows.Next() {
		var i GetInboundOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.InboundOrderID,
			&i.SkuID,
			&i.PkuID,
			&i.ExpectedQuantity,
			&i.ReceivedQuantity,
			&i.SkuUuid,
			&i.SkuName,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementInboundLineReceived = `-- name: IncrementInboundLineReceived :one
UPDATE inbound_order_lines
SET received_quantity = received_quantity + $2
WHERE id = $1
RETURNING id, inbound_order_id, sku_id, pku_id, expected_quantity, received_quantity
`

type IncrementInboundLineReceivedParams struct {
	ID               int64
	ReceivedQuantity pgtype.Numeric
}

func (q *Queries) IncrementInboundLineReceived(ctx context.Context, arg IncrementInboundLineReceivedParams) (InboundOrderLine, error) {
	row := q.db.QueryRow(ctx, incrementInboundLineReceived, arg.ID, arg.ReceivedQuantity)
	var i InboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.InboundOrderID,
		&i.SkuID,
		&i.PkuID,
		&i.ExpectedQuantity,
		&i.ReceivedQuantity,
	)
	return i, err
}

const updateInboundOrderStatus = `-- name: UpdateInboundOrderStatus :one
UPDATE inbound_orders
SET
    status = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, po_number, tenant_id, vendor_name, version, status, expected_delivery, created_at, updated_at
`

type UpdateInboundOrderStatusParams struct {
	ID      int64
	Status  InboundOrderStatus
	Version int32
}

func (q *Queries) UpdateInboundOrderStatus(ctx context.Context, arg UpdateInboundOrderStatusParams) (InboundOrder, error) {
	row := q.db.QueryRow(ctx, updateInboundOrderStatus, arg.ID, arg.Status, arg.Version)
	var i InboundOrder
	err := row.Scan(
		&i.ID,
		&i.PoNumber,
		&i.TenantID,
		&i.VendorName,
		&i.Version,
		&i.Status,
		&i.ExpectedDelivery,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReceiptStatus = `-- name: UpdateReceiptStatus :one
UPDATE receipts
SET status = $2
WHERE id = $1
RETURNING id, inbound_order_id, receipt_number, status, operator_id, received_at
`

type UpdateReceiptStatusParams struct {
	ID     int64
	Status ReceiptStatus
}

func (q *Queries) UpdateReceiptStatus(ctx context.Context, arg UpdateReceiptStatusParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, updateReceiptStatus, arg.ID, arg.Status)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.InboundOrderID,
		&i.ReceiptNumber,
		&i.Status,
		&i.OperatorID,
		&i.ReceivedAt,
	)
	return i, err
}
