// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAllocation = `-- name: CreateAllocation :one
INSERT INTO inventory_allocations (
    order_line_id,
    balance_id,
    sku_id,
    allocated_quantity
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, order_line_id, balance_id, sku_id, allocated_quantity, picked_quantity, created_at
`

type CreateAllocationParams struct {
	OrderLineID       int64
	BalanceID         int64
	SkuID             int64
	AllocatedQuantity pgtype.Numeric
}

func (q *Queries) CreateAllocation(ctx context.Context, arg CreateAllocationParams) (InventoryAllocation, error) {
	row := q.db.QueryRow(ctx, createAllocation,
		arg.OrderLineID,
		arg.BalanceID,
		arg.SkuID,
		arg.AllocatedQuantity,
	)
	var i InventoryAllocation
	err := row.Scan(
		&i.ID,
		&i.OrderLineID,
		&i.BalanceID,
		&i.SkuID,
		&i.AllocatedQuantity,
		&i.PickedQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllocation = `-- name: DeleteAllocation :execrows
DELETE FROM inventory_allocations
WHERE id = $1
`

func (q *Queries) DeleteAllocation(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findReservableBalances = `-- name: FindReservableBalances :many
SELECT b.id, b.node_id, b.sku_id, b.pku_id, b.lot_id, b.is_sealed, b.package_count, b.version, b.on_hand, b.allocated, b.updated_at
FROM inventory_balances b
LEFT JOIN lots l ON b.lot_id = l.id
WHERE b.sku_id = $1
  AND b.pku_id = $2
  AND (b.on_hand - b.allocated) >= $3
  AND (l.status IS NULL OR l.status = 'AVAILABLE')
ORDER BY l.expires_at ASC NULLS LAST, b.on_hand DESC
`

type FindReservableBalancesParams struct {
	SkuID  int64
	PkuID  int64
	OnHand pgtype.Numeric
}

func (q *Queries) FindReservableBalances(ctx context.Context, arg FindReservableBalancesParams) ([]InventoryBalance, error) {
	rows, err := q.db.Query(ctx, findReservableBalances, arg.SkuID, arg.PkuID, arg.OnHand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryBalance
	for rows.Next() {
		var i InventoryBalance
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.IsSealed,
			&i.PackageCount,
			&i.Version,
			&i.OnHand,
			&i.Allocated,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllocationsByOrderLine = `-- name: GetAllocationsByOrderLine :many
SELECT id, order_line_id, balance_id, sku_id, allocated_quantity, picked_quantity, created_at FROM inventory_allocations
WHERE order_line_id = $1
`

func (q *Queries) GetAllocationsByOrderLine(ctx context.Context, orderLineID int64) ([]InventoryAllocation, error) {
	rows, err := q.db.Query(ctx, getAllocationsByOrderLine, orderLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryAllocation
	for rows.Next() {
		var i InventoryAllocation
		if err := rows.Scan(
			&i.ID,
			&i.OrderLineID,
			&i.BalanceID,
			&i.SkuID,
			&i.AllocatedQuantity,
			&i.PickedQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementAllocationPicked = `-- name: IncrementAllocationPicked :one
UPDATE inventory_allocations
SET picked_quantity = picked_quantity + $2
WHERE id = $1 AND (picked_quantity + $2) <= allocated_quantity
RETURNING id, order_line_id, balance_id, sku_id, allocated_quantity, picked_quantity, created_at
`

type IncrementAllocationPickedParams struct {
	ID             int64
	PickedQuantity pgtype.Numeric
}

func (q *Queries) IncrementAllocationPicked(ctx context.Context, arg IncrementAllocationPickedParams) (InventoryAllocation, error) {
	row := q.db.QueryRow(ctx, incrementAllocationPicked, arg.ID, arg.PickedQuantity)
	var i InventoryAllocation
	err := row.Scan(
		&i.ID,
		&i.OrderLineID,
		&i.BalanceID,
		&i.SkuID,
		&i.AllocatedQuantity,
		&i.PickedQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const insertMovement = `-- name: InsertMovement :one
INSERT INTO inventory_movements (
    sku_id,
    pku_id,
    lot_id,
    package_count,
    quantity,
    source_node_id,
    destination_node_id,
    reason,
    reference_id,
    allocation_id,
    is_sealed,
    operator_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, sku_id, pku_id, lot_id, package_count, quantity, source_node_id, destination_node_id, reason, reference_id, allocation_id, is_sealed, operator_id, created_at
`

type InsertMovementParams struct {
	SkuID             int64
	PkuID             int64
	LotID             pgtype.Int8
	PackageCount      pgtype.Numeric
	Quantity          pgtype.Numeric
	SourceNodeID      pgtype.Int8
	DestinationNodeID pgtype.Int8
	Reason            MovementReason
	ReferenceID       pgtype.Text
	AllocationID      pgtype.Int8
	IsSealed          bool
	OperatorID        string
}

func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, insertMovement,
		arg.SkuID,
		arg.PkuID,
		arg.LotID,
		arg.PackageCount,
		arg.Quantity,
		arg.SourceNodeID,
		arg.DestinationNodeID,
		arg.Reason,
		arg.ReferenceID,
		arg.AllocationID,
		arg.IsSealed,
		arg.OperatorID,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.PackageCount,
		&i.Quantity,
		&i.SourceNodeID,
		&i.DestinationNodeID,
		&i.Reason,
		&i.ReferenceID,
		&i.AllocationID,
		&i.IsSealed,
		&i.OperatorID,
		&i.CreatedAt,
	)
	return i, err
}

const listBalancesByNode = `-- name: ListBalancesByNode :many
SELECT b.id, b.node_id, b.sku_id, b.pku_id, b.lot_id, b.is_sealed, b.package_count, b.version, b.on_hand, b.allocated, b.updated_at, s.id AS sku_uuid, s.name AS sku_name, p.unit_name
FROM inventory_balances b
JOIN stock_keeping_units s ON b.sku_id = s.id
JOIN sku_packaging_units p ON b.pku_id = p.id
WHERE b.node_id = $1
`

type ListBalancesByNodeRow struct {
	ID           int64
	NodeID       int64
	SkuID        int64
	PkuID        int64
	LotID        pgtype.Int8
	IsSealed     bool
	PackageCount pgtype.Numeric
	Version      int32
	OnHand       pgtype.Numeric
	Allocated    pgtype.Numeric
	UpdatedAt    pgtype.Timestamptz
	SkuUuid      int64
	SkuName      string
	UnitName     string
}

func (q *Queries) ListBalancesByNode(ctx context.Context, nodeID int64) ([]ListBalancesByNodeRow, error) {
	rows, err := q.db.Query(ctx, listBalancesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBalancesByNodeRow
	for rows.Next() {
		var i ListBalancesByNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.IsSealed,
			&i.PackageCount,
			&i.Version,
			&i.OnHand,
			&i.Allocated,
			&i.UpdatedAt,
			&i.SkuUuid,
			&i.SkuName,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByNode = `-- name: ListMovementsByNode :many
SELECT id, sku_id, pku_id, lot_id, package_count, quantity, source_node_id, destination_node_id, reason, reference_id, allocation_id, is_sealed, operator_id, created_at FROM inventory_movements
WHERE source_node_id = $1 OR destination_node_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMovementsByNodeParams struct {
	SourceNodeID pgtype.Int8
	Limit        int32
	Offset       int32
}

func (q *Queries) ListMovementsByNode(ctx context.Context, arg ListMovementsByNodeParams) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByNode, arg.SourceNodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMovement
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.PackageCount,
			&i.Quantity,
			&i.SourceNodeID,
			&i.DestinationNodeID,
			&i.Reason,
			&i.ReferenceID,
			&i.AllocationID,
			&i.IsSealed,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsBySKU = `-- name: ListMovementsBySKU :many
SELECT id, sku_id, pku_id, lot_id, package_count, quantity, source_node_id, destination_node_id, reason, reference_id, allocation_id, is_sealed, operator_id, created_at FROM inventory_movements
WHERE sku_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMovementsBySKUParams struct {
	SkuID  int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListMovementsBySKU(ctx context.Context, arg ListMovementsBySKUParams) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsBySKU, arg.SkuID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMovement
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.PackageCount,
			&i.Quantity,
			&i.SourceNodeID,
			&i.DestinationNodeID,
			&i.Reason,
			&i.ReferenceID,
			&i.AllocationID,
			&i.IsSealed,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalanceForUpdate = `-- name: LockBalanceForUpdate :one
SELECT id, on_hand, package_count, allocated, version 
FROM inventory_balances 
WHERE node_id = $1 AND pku_id = $2 
  AND lot_id IS NOT DISTINCT FROM $3 AND is_sealed = $4
FOR UPDATE
`

type LockBalanceForUpdateParams struct {
	NodeID   int64
	PkuID    int64
	LotID    pgtype.Int8
	IsSealed bool
}

type LockBalanceForUpdateRow struct {
	ID           int64
	OnHand       pgtype.Numeric
	PackageCount pgtype.Numeric
	Allocated    pgtype.Numeric
	Version      int32
}

func (q *Queries) LockBalanceForUpdate(ctx context.Context, arg LockBalanceForUpdateParams) (LockBalanceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockBalanceForUpdate,
		arg.NodeID,
		arg.PkuID,
		arg.LotID,
		arg.IsSealed,
	)
	var i LockBalanceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OnHand,
		&i.PackageCount,
		&i.Allocated,
		&i.Version,
	)
	return i, err
}

const projectDestinationAddition = `-- name: ProjectDestinationAddition :exec
INSERT INTO inventory_balances (
    node_id, sku_id, pku_id, lot_id, is_sealed, on_hand, package_count
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (node_id, pku_id, lot_id, is_sealed) 
DO UPDATE SET 
    on_hand = inventory_balances.on_hand + EXCLUDED.on_hand,
    package_count = inventory_balances.package_count + EXCLUDED.package_count,
    version = inventory_balances.version + 1,
    updated_at = now()
`

type ProjectDestinationAdditionParams struct {
	NodeID       int64
	SkuID        int64
	PkuID        int64
	LotID        pgtype.Int8
	IsSealed     bool
	OnHand       pgtype.Numeric
	PackageCount pgtype.Numeric
}

func (q *Queries) ProjectDestinationAddition(ctx context.Context, arg ProjectDestinationAdditionParams) error {
	_, err := q.db.Exec(ctx, projectDestinationAddition,
		arg.NodeID,
		arg.SkuID,
		arg.PkuID,
		arg.LotID,
		arg.IsSealed,
		arg.OnHand,
		arg.PackageCount,
	)
	return err
}

const projectSourceDeduction = `-- name: ProjectSourceDeduction :execrows
UPDATE inventory_balances
SET on_hand = on_hand - $1, 
    package_count = package_count - $2, 
    version = version + 1,
    updated_at = now()
WHERE id = $3 AND version = $4
`

type ProjectSourceDeductionParams struct {
	OnHand       pgtype.Numeric
	PackageCount pgtype.Numeric
	ID           int64
	Version      int32
}

func (q *Queries) ProjectSourceDeduction(ctx context.Context, arg ProjectSourceDeductionParams) (int64, error) {
	result, err := q.db.Exec(ctx, projectSourceDeduction,
		arg.OnHand,
		arg.PackageCount,
		arg.ID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBalanceAllocation = `-- name: UpdateBalanceAllocation :execrows
UPDATE inventory_balances
SET allocated = allocated + $1,
    version = version + 1,
    updated_at = now()
WHERE id = $2 AND version = $3 AND (on_hand - allocated - $1) >= 0
`

type UpdateBalanceAllocationParams struct {
	Allocated pgtype.Numeric
	ID        int64
	Version   int32
}

func (q *Queries) UpdateBalanceAllocation(ctx context.Context, arg UpdateBalanceAllocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBalanceAllocation, arg.Allocated, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
