// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyBalanceAllocation = `-- name: ApplyBalanceAllocation :one
UPDATE inventory_balances
SET
    allocated = allocated + $2,
    updated_at = now()
WHERE id = $1 AND (on_hand - allocated) >= $2
RETURNING id, node_id, sku_id, pku_id, lot_id, is_sealed, package_count, on_hand, allocated, updated_at
`

type ApplyBalanceAllocationParams struct {
	ID        int64
	Allocated pgtype.Numeric
}

func (q *Queries) ApplyBalanceAllocation(ctx context.Context, arg ApplyBalanceAllocationParams) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, applyBalanceAllocation, arg.ID, arg.Allocated)
	var i InventoryBalance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.IsSealed,
		&i.PackageCount,
		&i.OnHand,
		&i.Allocated,
		&i.UpdatedAt,
	)
	return i, err
}

const createAllocation = `-- name: CreateAllocation :one
INSERT INTO inventory_allocations (
    order_line_id,
    balance_id,
    allocated_quantity
) VALUES (
    $1, $2, $3
)
RETURNING id, order_line_id, balance_id, allocated_quantity, created_at
`

type CreateAllocationParams struct {
	OrderLineID       int64
	BalanceID         int64
	AllocatedQuantity pgtype.Numeric
}

func (q *Queries) CreateAllocation(ctx context.Context, arg CreateAllocationParams) (InventoryAllocation, error) {
	row := q.db.QueryRow(ctx, createAllocation, arg.OrderLineID, arg.BalanceID, arg.AllocatedQuantity)
	var i InventoryAllocation
	err := row.Scan(
		&i.ID,
		&i.OrderLineID,
		&i.BalanceID,
		&i.AllocatedQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const deductBalanceFulfillment = `-- name: DeductBalanceFulfillment :one
UPDATE inventory_balances
SET
    on_hand = on_hand - $2,
    allocated = allocated - $2,
    package_count = GREATEST(0, package_count - $3),
    updated_at = now()
WHERE id = $1 AND allocated >= $2 AND on_hand >= $2
RETURNING id, node_id, sku_id, pku_id, lot_id, is_sealed, package_count, on_hand, allocated, updated_at
`

type DeductBalanceFulfillmentParams struct {
	ID           int64
	OnHand       pgtype.Numeric
	PackageCount pgtype.Numeric
}

func (q *Queries) DeductBalanceFulfillment(ctx context.Context, arg DeductBalanceFulfillmentParams) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, deductBalanceFulfillment, arg.ID, arg.OnHand, arg.PackageCount)
	var i InventoryBalance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.IsSealed,
		&i.PackageCount,
		&i.OnHand,
		&i.Allocated,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllocation = `-- name: DeleteAllocation :execrows
DELETE FROM inventory_allocations
WHERE id = $1
`

func (q *Queries) DeleteAllocation(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllocation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findReservableBalances = `-- name: FindReservableBalances :many
SELECT b.id, b.node_id, b.sku_id, b.pku_id, b.lot_id, b.is_sealed, b.package_count, b.on_hand, b.allocated, b.updated_at
FROM inventory_balances b
LEFT JOIN lots l ON b.lot_id = l.id
WHERE b.sku_id = $1
  AND b.pku_id = $2
  AND (b.on_hand - b.allocated) >= $3
  AND (l.status IS NULL OR l.status = 'AVAILABLE')
ORDER BY l.expires_at ASC NULLS LAST, b.on_hand DESC
`

type FindReservableBalancesParams struct {
	SkuID  int64
	PkuID  int64
	OnHand pgtype.Numeric
}

func (q *Queries) FindReservableBalances(ctx context.Context, arg FindReservableBalancesParams) ([]InventoryBalance, error) {
	rows, err := q.db.Query(ctx, findReservableBalances, arg.SkuID, arg.PkuID, arg.OnHand)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryBalance
	for rows.Next() {
		var i InventoryBalance
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.IsSealed,
			&i.PackageCount,
			&i.OnHand,
			&i.Allocated,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllocationsByOrderLine = `-- name: GetAllocationsByOrderLine :many
SELECT id, order_line_id, balance_id, allocated_quantity, created_at FROM inventory_allocations
WHERE order_line_id = $1
`

func (q *Queries) GetAllocationsByOrderLine(ctx context.Context, orderLineID int64) ([]InventoryAllocation, error) {
	rows, err := q.db.Query(ctx, getAllocationsByOrderLine, orderLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryAllocation
	for rows.Next() {
		var i InventoryAllocation
		if err := rows.Scan(
			&i.ID,
			&i.OrderLineID,
			&i.BalanceID,
			&i.AllocatedQuantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT id, node_id, sku_id, pku_id, lot_id, is_sealed, package_count, on_hand, allocated, updated_at FROM inventory_balances
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetBalanceForUpdate(ctx context.Context, id int64) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, getBalanceForUpdate, id)
	var i InventoryBalance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.IsSealed,
		&i.PackageCount,
		&i.OnHand,
		&i.Allocated,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryBalanceByID = `-- name: GetInventoryBalanceByID :one
SELECT id, node_id, sku_id, pku_id, lot_id, is_sealed, package_count, on_hand, allocated, updated_at FROM inventory_balances
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInventoryBalanceByID(ctx context.Context, id int64) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, getInventoryBalanceByID, id)
	var i InventoryBalance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.IsSealed,
		&i.PackageCount,
		&i.OnHand,
		&i.Allocated,
		&i.UpdatedAt,
	)
	return i, err
}

const listBalancesByNode = `-- name: ListBalancesByNode :many
SELECT b.id, b.node_id, b.sku_id, b.pku_id, b.lot_id, b.is_sealed, b.package_count, b.on_hand, b.allocated, b.updated_at, s.id, s.name AS sku_name, p.unit_name
FROM inventory_balances b
JOIN stock_keeping_units s ON b.sku_id = s.id
JOIN sku_packaging_units p ON b.pku_id = p.id
WHERE b.node_id = $1
`

type ListBalancesByNodeRow struct {
	ID           int64
	NodeID       int64
	SkuID        int64
	PkuID        int64
	LotID        pgtype.Int8
	IsSealed     bool
	PackageCount pgtype.Numeric
	OnHand       pgtype.Numeric
	Allocated    pgtype.Numeric
	UpdatedAt    pgtype.Timestamptz
	ID_2         int64
	SkuName      string
	UnitName     string
}

func (q *Queries) ListBalancesByNode(ctx context.Context, nodeID int64) ([]ListBalancesByNodeRow, error) {
	rows, err := q.db.Query(ctx, listBalancesByNode, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBalancesByNodeRow
	for rows.Next() {
		var i ListBalancesByNodeRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.IsSealed,
			&i.PackageCount,
			&i.OnHand,
			&i.Allocated,
			&i.UpdatedAt,
			&i.ID_2,
			&i.SkuName,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByNode = `-- name: ListMovementsByNode :many
SELECT id, sku_id, pku_id, lot_id, package_count, quantity, source_node_id, destination_node_id, reason, reference_id, allocation_id, is_sealed, operator_id, created_at FROM inventory_movements
WHERE source_node_id = $1 OR destination_node_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMovementsByNodeParams struct {
	SourceNodeID pgtype.Int8
	Limit        int32
	Offset       int32
}

func (q *Queries) ListMovementsByNode(ctx context.Context, arg ListMovementsByNodeParams) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByNode, arg.SourceNodeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMovement
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.PackageCount,
			&i.Quantity,
			&i.SourceNodeID,
			&i.DestinationNodeID,
			&i.Reason,
			&i.ReferenceID,
			&i.AllocationID,
			&i.IsSealed,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsBySKU = `-- name: ListMovementsBySKU :many
SELECT id, sku_id, pku_id, lot_id, package_count, quantity, source_node_id, destination_node_id, reason, reference_id, allocation_id, is_sealed, operator_id, created_at FROM inventory_movements
WHERE sku_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMovementsBySKUParams struct {
	SkuID  int64
	Limit  int32
	Offset int32
}

func (q *Queries) ListMovementsBySKU(ctx context.Context, arg ListMovementsBySKUParams) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsBySKU, arg.SkuID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryMovement
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.PackageCount,
			&i.Quantity,
			&i.SourceNodeID,
			&i.DestinationNodeID,
			&i.Reason,
			&i.ReferenceID,
			&i.AllocationID,
			&i.IsSealed,
			&i.OperatorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMovement = `-- name: RecordMovement :one
INSERT INTO inventory_movements (
    sku_id,
    pku_id,
    lot_id,
    package_count,
    quantity,
    source_node_id,
    destination_node_id,
    reason,
    reference_id,
    allocation_id,
    is_sealed,
    operator_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, sku_id, pku_id, lot_id, package_count, quantity, source_node_id, destination_node_id, reason, reference_id, allocation_id, is_sealed, operator_id, created_at
`

type RecordMovementParams struct {
	SkuID             int64
	PkuID             int64
	LotID             pgtype.Int8
	PackageCount      pgtype.Numeric
	Quantity          pgtype.Numeric
	SourceNodeID      pgtype.Int8
	DestinationNodeID pgtype.Int8
	Reason            MovementReason
	ReferenceID       pgtype.Text
	AllocationID      pgtype.Int8
	IsSealed          bool
	OperatorID        string
}

func (q *Queries) RecordMovement(ctx context.Context, arg RecordMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, recordMovement,
		arg.SkuID,
		arg.PkuID,
		arg.LotID,
		arg.PackageCount,
		arg.Quantity,
		arg.SourceNodeID,
		arg.DestinationNodeID,
		arg.Reason,
		arg.ReferenceID,
		arg.AllocationID,
		arg.IsSealed,
		arg.OperatorID,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.PackageCount,
		&i.Quantity,
		&i.SourceNodeID,
		&i.DestinationNodeID,
		&i.Reason,
		&i.ReferenceID,
		&i.AllocationID,
		&i.IsSealed,
		&i.OperatorID,
		&i.CreatedAt,
	)
	return i, err
}

const releaseBalanceAllocation = `-- name: ReleaseBalanceAllocation :one
UPDATE inventory_balances
SET
    allocated = allocated - $2,
    updated_at = now()
WHERE id = $1 AND allocated >= $2
RETURNING id, node_id, sku_id, pku_id, lot_id, is_sealed, package_count, on_hand, allocated, updated_at
`

type ReleaseBalanceAllocationParams struct {
	ID        int64
	Allocated pgtype.Numeric
}

func (q *Queries) ReleaseBalanceAllocation(ctx context.Context, arg ReleaseBalanceAllocationParams) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, releaseBalanceAllocation, arg.ID, arg.Allocated)
	var i InventoryBalance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.IsSealed,
		&i.PackageCount,
		&i.OnHand,
		&i.Allocated,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertInventoryBalance = `-- name: UpsertInventoryBalance :one
INSERT INTO inventory_balances (
    node_id,
    sku_id,
    pku_id,
    lot_id,
    is_sealed,
    package_count,
    on_hand,
    allocated
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 0
)
ON CONFLICT (node_id, pku_id, lot_id, is_sealed)
DO UPDATE SET
    package_count = inventory_balances.package_count + EXCLUDED.package_count,
    on_hand = inventory_balances.on_hand + EXCLUDED.on_hand,
    updated_at = now()
RETURNING id, node_id, sku_id, pku_id, lot_id, is_sealed, package_count, on_hand, allocated, updated_at
`

type UpsertInventoryBalanceParams struct {
	NodeID       int64
	SkuID        int64
	PkuID        int64
	LotID        pgtype.Int8
	IsSealed     bool
	PackageCount pgtype.Numeric
	OnHand       pgtype.Numeric
}

func (q *Queries) UpsertInventoryBalance(ctx context.Context, arg UpsertInventoryBalanceParams) (InventoryBalance, error) {
	row := q.db.QueryRow(ctx, upsertInventoryBalance,
		arg.NodeID,
		arg.SkuID,
		arg.PkuID,
		arg.LotID,
		arg.IsSealed,
		arg.PackageCount,
		arg.OnHand,
	)
	var i InventoryBalance
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.IsSealed,
		&i.PackageCount,
		&i.OnHand,
		&i.Allocated,
		&i.UpdatedAt,
	)
	return i, err
}
