// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStorageNode = `-- name: CreateStorageNode :one
INSERT INTO storage_nodes (
    parent_id,
    path,
    code,
    node_type,
    is_movable,
    max_weight_kg,
    max_volume_cm3,
    is_active
) VALUES (
    $1,
    ''::ltree, -- Trigger set_storage_node_path computes the real path
    $2, $3, $4, $5, $6, $7
)
RETURNING id, parent_id, path::text AS path, code, node_type, is_movable, max_weight_kg, max_volume_cm3, is_active, created_at
`

type CreateStorageNodeParams struct {
	ParentID     pgtype.Int8
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
}

type CreateStorageNodeRow struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateStorageNode(ctx context.Context, arg CreateStorageNodeParams) (CreateStorageNodeRow, error) {
	row := q.db.QueryRow(ctx, createStorageNode,
		arg.ParentID,
		arg.Code,
		arg.NodeType,
		arg.IsMovable,
		arg.MaxWeightKg,
		arg.MaxVolumeCm3,
		arg.IsActive,
	)
	var i CreateStorageNodeRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Code,
		&i.NodeType,
		&i.IsMovable,
		&i.MaxWeightKg,
		&i.MaxVolumeCm3,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStorageNode = `-- name: DeleteStorageNode :execrows
DELETE FROM storage_nodes
WHERE id = $1
`

func (q *Queries) DeleteStorageNode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStorageNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStorageNodeByCode = `-- name: GetStorageNodeByCode :one
SELECT id, parent_id, path::text AS path, code, node_type, is_movable, max_weight_kg, max_volume_cm3, is_active, created_at
FROM storage_nodes
WHERE code = $1 LIMIT 1
`

type GetStorageNodeByCodeRow struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetStorageNodeByCode(ctx context.Context, code string) (GetStorageNodeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getStorageNodeByCode, code)
	var i GetStorageNodeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Code,
		&i.NodeType,
		&i.IsMovable,
		&i.MaxWeightKg,
		&i.MaxVolumeCm3,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getStorageNodeByID = `-- name: GetStorageNodeByID :one
SELECT id, parent_id, path::text AS path, code, node_type, is_movable, max_weight_kg, max_volume_cm3, is_active, created_at
FROM storage_nodes
WHERE id = $1 LIMIT 1
`

type GetStorageNodeByIDRow struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetStorageNodeByID(ctx context.Context, id int64) (GetStorageNodeByIDRow, error) {
	row := q.db.QueryRow(ctx, getStorageNodeByID, id)
	var i GetStorageNodeByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Code,
		&i.NodeType,
		&i.IsMovable,
		&i.MaxWeightKg,
		&i.MaxVolumeCm3,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listDirectChildNodes = `-- name: ListDirectChildNodes :many
SELECT id, parent_id, path::text AS path, code, node_type, is_movable, max_weight_kg, max_volume_cm3, is_active, created_at
FROM storage_nodes
WHERE parent_id = $1
ORDER BY code ASC
`

type ListDirectChildNodesRow struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListDirectChildNodes(ctx context.Context, parentID pgtype.Int8) ([]ListDirectChildNodesRow, error) {
	rows, err := q.db.Query(ctx, listDirectChildNodes, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDirectChildNodesRow
	for rows.Next() {
		var i ListDirectChildNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Path,
			&i.Code,
			&i.NodeType,
			&i.IsMovable,
			&i.MaxWeightKg,
			&i.MaxVolumeCm3,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtreeNodes = `-- name: ListSubtreeNodes :many
SELECT 
    node.id, 
    node.parent_id, 
    node.path::text AS path, 
    node.code, 
    node.node_type, 
    node.is_movable, 
    node.max_weight_kg, 
    node.max_volume_cm3, 
    node.is_active, 
    node.created_at
FROM storage_nodes AS node
WHERE node.path <@ (
    SELECT root.path 
    FROM storage_nodes AS root 
    WHERE root.id = $1
)
ORDER BY node.path
`

type ListSubtreeNodesRow struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListSubtreeNodes(ctx context.Context, id int64) ([]ListSubtreeNodesRow, error) {
	rows, err := q.db.Query(ctx, listSubtreeNodes, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubtreeNodesRow
	for rows.Next() {
		var i ListSubtreeNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Path,
			&i.Code,
			&i.NodeType,
			&i.IsMovable,
			&i.MaxWeightKg,
			&i.MaxVolumeCm3,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reparentStorageNode = `-- name: ReparentStorageNode :one
UPDATE storage_nodes
SET parent_id = $2
WHERE id = $1
RETURNING id, parent_id, path::text AS path, code, node_type, is_movable, max_weight_kg, max_volume_cm3, is_active, created_at
`

type ReparentStorageNodeParams struct {
	ID       int64
	ParentID pgtype.Int8
}

type ReparentStorageNodeRow struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ReparentStorageNode(ctx context.Context, arg ReparentStorageNodeParams) (ReparentStorageNodeRow, error) {
	row := q.db.QueryRow(ctx, reparentStorageNode, arg.ID, arg.ParentID)
	var i ReparentStorageNodeRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Code,
		&i.NodeType,
		&i.IsMovable,
		&i.MaxWeightKg,
		&i.MaxVolumeCm3,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateStorageNodeDetails = `-- name: UpdateStorageNodeDetails :one
UPDATE storage_nodes
SET
    code = COALESCE($1, code),
    is_movable = COALESCE($2, is_movable),
    max_weight_kg = COALESCE($3, max_weight_kg),
    max_volume_cm3 = COALESCE($4, max_volume_cm3),
    is_active = COALESCE($5, is_active)
WHERE id = $6
RETURNING id, parent_id, path::text AS path, code, node_type, is_movable, max_weight_kg, max_volume_cm3, is_active, created_at
`

type UpdateStorageNodeDetailsParams struct {
	Code         pgtype.Text
	IsMovable    pgtype.Bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     pgtype.Bool
	ID           int64
}

type UpdateStorageNodeDetailsRow struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateStorageNodeDetails(ctx context.Context, arg UpdateStorageNodeDetailsParams) (UpdateStorageNodeDetailsRow, error) {
	row := q.db.QueryRow(ctx, updateStorageNodeDetails,
		arg.Code,
		arg.IsMovable,
		arg.MaxWeightKg,
		arg.MaxVolumeCm3,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateStorageNodeDetailsRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Path,
		&i.Code,
		&i.NodeType,
		&i.IsMovable,
		&i.MaxWeightKg,
		&i.MaxVolumeCm3,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
