// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InboundOrderStatus string

const (
	InboundOrderStatusDRAFT             InboundOrderStatus = "DRAFT"
	InboundOrderStatusISSUED            InboundOrderStatus = "ISSUED"
	InboundOrderStatusPARTIALLYRECEIVED InboundOrderStatus = "PARTIALLY_RECEIVED"
	InboundOrderStatusRECEIVED          InboundOrderStatus = "RECEIVED"
	InboundOrderStatusCANCELLED         InboundOrderStatus = "CANCELLED"
)

func (e *InboundOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboundOrderStatus(s)
	case string:
		*e = InboundOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InboundOrderStatus: %T", src)
	}
	return nil
}

type NullInboundOrderStatus struct {
	InboundOrderStatus InboundOrderStatus
	Valid              bool // Valid is true if InboundOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboundOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InboundOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboundOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboundOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboundOrderStatus), nil
}

type LotStatus string

const (
	LotStatusAVAILABLE   LotStatus = "AVAILABLE"
	LotStatusQUARANTINED LotStatus = "QUARANTINED"
	LotStatusEXPIRED     LotStatus = "EXPIRED"
	LotStatusRECALLED    LotStatus = "RECALLED"
)

func (e *LotStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LotStatus(s)
	case string:
		*e = LotStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LotStatus: %T", src)
	}
	return nil
}

type NullLotStatus struct {
	LotStatus LotStatus
	Valid     bool // Valid is true if LotStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLotStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LotStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LotStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLotStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LotStatus), nil
}

type MovementReason string

const (
	MovementReasonRECEIVING        MovementReason = "RECEIVING"
	MovementReasonPUTAWAY          MovementReason = "PUTAWAY"
	MovementReasonPICK             MovementReason = "PICK"
	MovementReasonREPLENISHMENT    MovementReason = "REPLENISHMENT"
	MovementReasonINTERNALTRANSFER MovementReason = "INTERNAL_TRANSFER"
	MovementReasonBREAKPACKAGE     MovementReason = "BREAK_PACKAGE"
	MovementReasonREPACKAGE        MovementReason = "REPACKAGE"
	MovementReasonCYCLECOUNT       MovementReason = "CYCLE_COUNT"
	MovementReasonSCRAPDAMAGED     MovementReason = "SCRAP_DAMAGED"
	MovementReasonRETURN           MovementReason = "RETURN"
)

func (e *MovementReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovementReason(s)
	case string:
		*e = MovementReason(s)
	default:
		return fmt.Errorf("unsupported scan type for MovementReason: %T", src)
	}
	return nil
}

type NullMovementReason struct {
	MovementReason MovementReason
	Valid          bool // Valid is true if MovementReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovementReason) Scan(value interface{}) error {
	if value == nil {
		ns.MovementReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovementReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovementReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovementReason), nil
}

type OrderStatus string

const (
	OrderStatusPENDING            OrderStatus = "PENDING"
	OrderStatusALLOCATED          OrderStatus = "ALLOCATED"
	OrderStatusPARTIALLYALLOCATED OrderStatus = "PARTIALLY_ALLOCATED"
	OrderStatusPICKING            OrderStatus = "PICKING"
	OrderStatusPACKED             OrderStatus = "PACKED"
	OrderStatusSHIPPED            OrderStatus = "SHIPPED"
	OrderStatusCANCELLED          OrderStatus = "CANCELLED"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type StorageNodeType string

const (
	StorageNodeTypeWAREHOUSE StorageNodeType = "WAREHOUSE"
	StorageNodeTypeZONE      StorageNodeType = "ZONE"
	StorageNodeTypeAISLE     StorageNodeType = "AISLE"
	StorageNodeTypeBAY       StorageNodeType = "BAY"
	StorageNodeTypeBIN       StorageNodeType = "BIN"
	StorageNodeTypePALLET    StorageNodeType = "PALLET"
	StorageNodeTypeTOTE      StorageNodeType = "TOTE"
	StorageNodeTypeCART      StorageNodeType = "CART"
)

func (e *StorageNodeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StorageNodeType(s)
	case string:
		*e = StorageNodeType(s)
	default:
		return fmt.Errorf("unsupported scan type for StorageNodeType: %T", src)
	}
	return nil
}

type NullStorageNodeType struct {
	StorageNodeType StorageNodeType
	Valid           bool // Valid is true if StorageNodeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStorageNodeType) Scan(value interface{}) error {
	if value == nil {
		ns.StorageNodeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StorageNodeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStorageNodeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StorageNodeType), nil
}

type TaskStatus string

const (
	TaskStatusPENDING    TaskStatus = "PENDING"
	TaskStatusASSIGNED   TaskStatus = "ASSIGNED"
	TaskStatusINPROGRESS TaskStatus = "IN_PROGRESS"
	TaskStatusCOMPLETED  TaskStatus = "COMPLETED"
	TaskStatusCANCELLED  TaskStatus = "CANCELLED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TaskType string

const (
	TaskTypePUTAWAY      TaskType = "PUTAWAY"
	TaskTypePICK         TaskType = "PICK"
	TaskTypeREPLENISH    TaskType = "REPLENISH"
	TaskTypeCOUNT        TaskType = "COUNT"
	TaskTypeRELOCATENODE TaskType = "RELOCATE_NODE"
)

func (e *TaskType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskType(s)
	case string:
		*e = TaskType(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskType: %T", src)
	}
	return nil
}

type NullTaskType struct {
	TaskType TaskType
	Valid    bool // Valid is true if TaskType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskType) Scan(value interface{}) error {
	if value == nil {
		ns.TaskType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskType), nil
}

type Uom string

const (
	UomEACH Uom = "EACH"
	UomKg   Uom = "Kg"
	UomG    Uom = "g"
	UomM    Uom = "m"
	UomL    Uom = "L"
	UomML   Uom = "mL"
)

func (e *Uom) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Uom(s)
	case string:
		*e = Uom(s)
	default:
		return fmt.Errorf("unsupported scan type for Uom: %T", src)
	}
	return nil
}

type NullUom struct {
	Uom   Uom
	Valid bool // Valid is true if Uom is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUom) Scan(value interface{}) error {
	if value == nil {
		ns.Uom, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Uom.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUom) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Uom), nil
}

type InboundOrder struct {
	ID               int64
	PoNumber         string
	VendorName       string
	Status           InboundOrderStatus
	ExpectedDelivery pgtype.Date
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type InboundOrderLine struct {
	ID               int64
	InboundOrderID   int64
	SkuID            int64
	PkuID            int64
	ExpectedQuantity pgtype.Numeric
	ReceivedQuantity pgtype.Numeric
}

type InventoryAllocation struct {
	ID                int64
	OrderLineID       int64
	BalanceID         int64
	AllocatedQuantity pgtype.Numeric
	CreatedAt         pgtype.Timestamptz
}

type InventoryBalance struct {
	ID           int64
	NodeID       int64
	SkuID        int64
	PkuID        int64
	LotID        pgtype.Int8
	IsSealed     bool
	PackageCount pgtype.Numeric
	OnHand       pgtype.Numeric
	Allocated    pgtype.Numeric
	UpdatedAt    pgtype.Timestamptz
}

type InventoryMovement struct {
	ID                int64
	SkuID             int64
	PkuID             int64
	LotID             pgtype.Int8
	PackageCount      pgtype.Numeric
	Quantity          pgtype.Numeric
	SourceNodeID      pgtype.Int8
	DestinationNodeID pgtype.Int8
	Reason            MovementReason
	ReferenceID       pgtype.Text
	AllocationID      pgtype.Int8
	IsSealed          bool
	OperatorID        string
	CreatedAt         pgtype.Timestamptz
}

type Lot struct {
	ID             int64
	SkuID          int64
	LotNumber      string
	Status         LotStatus
	ManufacturedAt pgtype.Date
	ExpiresAt      pgtype.Date
	ReceivedAt     pgtype.Timestamptz
}

type OutboundOrder struct {
	ID           int64
	OrderNumber  string
	CustomerName pgtype.Text
	Status       OrderStatus
	Priority     int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type OutboundOrderLine struct {
	ID                int64
	OrderID           int64
	SkuID             int64
	PkuID             int64
	RequestedQuantity pgtype.Numeric
	FulfilledQuantity pgtype.Numeric
}

type SkuPackagingUnit struct {
	ID                    int64
	SkuID                 int64
	UnitName              string
	ConversionFactor      pgtype.Numeric
	ParentPackagingUnitID pgtype.Int8
	IsBaseUnit            bool
	AllowsBreakBulk       bool
	Barcode               pgtype.Text
	TareWeightKg          pgtype.Numeric
	GrossVolumeCm3        pgtype.Numeric
}

type StockKeepingUnit struct {
	ID                  int64
	SkuCode             string
	Name                string
	BaseUom             Uom
	IsDiscrete          bool
	RequiresLotTracking bool
	Attributes          []byte
	CreatedAt           pgtype.Timestamptz
}

type StorageNode struct {
	ID           int64
	ParentID     pgtype.Int8
	Path         string
	Code         string
	NodeType     StorageNodeType
	IsMovable    bool
	MaxWeightKg  pgtype.Numeric
	MaxVolumeCm3 pgtype.Numeric
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type WarehouseTask struct {
	ID                 int64
	TaskType           TaskType
	Status             TaskStatus
	Priority           int32
	SkuID              pgtype.Int8
	PkuID              pgtype.Int8
	LotID              pgtype.Int8
	PackageCount       pgtype.Numeric
	Quantity           pgtype.Numeric
	TargetNodeID       pgtype.Int8
	SourceNodeID       pgtype.Int8
	DestinationNodeID  pgtype.Int8
	OrderLineID        pgtype.Int8
	AllocationID       pgtype.Int8
	AssignedOperatorID pgtype.Text
	CreatedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
}
