// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbound_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignHandlingUnitToShipment = `-- name: AssignHandlingUnitToShipment :exec
UPDATE handling_units
SET shipment_id = $2,
    tracking_number = COALESCE($3, tracking_number)
WHERE id = $1
`

type AssignHandlingUnitToShipmentParams struct {
	ID             int64
	ShipmentID     pgtype.Int8
	TrackingNumber pgtype.Text
}

func (q *Queries) AssignHandlingUnitToShipment(ctx context.Context, arg AssignHandlingUnitToShipmentParams) error {
	_, err := q.db.Exec(ctx, assignHandlingUnitToShipment, arg.ID, arg.ShipmentID, arg.TrackingNumber)
	return err
}

const createHandlingUnit = `-- name: CreateHandlingUnit :one
INSERT INTO handling_units (
    outbound_order_id,
    sscc,
    tare_weight_kg,
    gross_weight_kg
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, outbound_order_id, shipment_id, sscc, tracking_number, tare_weight_kg, gross_weight_kg, created_at
`

type CreateHandlingUnitParams struct {
	OutboundOrderID int64
	Sscc            pgtype.Text
	TareWeightKg    pgtype.Numeric
	GrossWeightKg   pgtype.Numeric
}

func (q *Queries) CreateHandlingUnit(ctx context.Context, arg CreateHandlingUnitParams) (HandlingUnit, error) {
	row := q.db.QueryRow(ctx, createHandlingUnit,
		arg.OutboundOrderID,
		arg.Sscc,
		arg.TareWeightKg,
		arg.GrossWeightKg,
	)
	var i HandlingUnit
	err := row.Scan(
		&i.ID,
		&i.OutboundOrderID,
		&i.ShipmentID,
		&i.Sscc,
		&i.TrackingNumber,
		&i.TareWeightKg,
		&i.GrossWeightKg,
		&i.CreatedAt,
	)
	return i, err
}

const createOutboundOrder = `-- name: CreateOutboundOrder :one
INSERT INTO outbound_orders (
    order_number,
    customer_name,
    status,
    priority
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, tenant_id, order_number, version, customer_name, status, priority, created_at, updated_at
`

type CreateOutboundOrderParams struct {
	OrderNumber  string
	CustomerName pgtype.Text
	Status       OrderStatus
	Priority     int32
}

func (q *Queries) CreateOutboundOrder(ctx context.Context, arg CreateOutboundOrderParams) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, createOutboundOrder,
		arg.OrderNumber,
		arg.CustomerName,
		arg.Status,
		arg.Priority,
	)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderNumber,
		&i.Version,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboundOrderLine = `-- name: CreateOutboundOrderLine :one
INSERT INTO outbound_order_lines (
    order_id,
    sku_id,
    pku_id,
    requested_quantity,
    fulfilled_quantity
) VALUES (
    $1, $2, $3, $4, 0
)
RETURNING id, order_id, sku_id, pku_id, requested_quantity, fulfilled_quantity
`

type CreateOutboundOrderLineParams struct {
	OrderID           int64
	SkuID             int64
	PkuID             int64
	RequestedQuantity pgtype.Numeric
}

func (q *Queries) CreateOutboundOrderLine(ctx context.Context, arg CreateOutboundOrderLineParams) (OutboundOrderLine, error) {
	row := q.db.QueryRow(ctx, createOutboundOrderLine,
		arg.OrderID,
		arg.SkuID,
		arg.PkuID,
		arg.RequestedQuantity,
	)
	var i OutboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SkuID,
		&i.PkuID,
		&i.RequestedQuantity,
		&i.FulfilledQuantity,
	)
	return i, err
}

const createShipment = `-- name: CreateShipment :one
INSERT INTO shipments (
    shipment_number,
    carrier_name,
    master_tracking_number,
    status
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, shipment_number, carrier_name, master_tracking_number, status, shipped_at, created_at
`

type CreateShipmentParams struct {
	ShipmentNumber       string
	CarrierName          string
	MasterTrackingNumber pgtype.Text
	Status               ShipmentStatus
}

func (q *Queries) CreateShipment(ctx context.Context, arg CreateShipmentParams) (Shipment, error) {
	row := q.db.QueryRow(ctx, createShipment,
		arg.ShipmentNumber,
		arg.CarrierName,
		arg.MasterTrackingNumber,
		arg.Status,
	)
	var i Shipment
	err := row.Scan(
		&i.ID,
		&i.ShipmentNumber,
		&i.CarrierName,
		&i.MasterTrackingNumber,
		&i.Status,
		&i.ShippedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOutboundOrder = `-- name: DeleteOutboundOrder :execrows
DELETE FROM outbound_orders
WHERE id = $1
`

func (q *Queries) DeleteOutboundOrder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutboundOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOutboundOrderByID = `-- name: GetOutboundOrderByID :one
SELECT id, tenant_id, order_number, version, customer_name, status, priority, created_at, updated_at FROM outbound_orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOutboundOrderByID(ctx context.Context, id int64) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, getOutboundOrderByID, id)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderNumber,
		&i.Version,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboundOrderByNumber = `-- name: GetOutboundOrderByNumber :one
SELECT id, tenant_id, order_number, version, customer_name, status, priority, created_at, updated_at FROM outbound_orders
WHERE order_number = $1 LIMIT 1
`

func (q *Queries) GetOutboundOrderByNumber(ctx context.Context, orderNumber string) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, getOutboundOrderByNumber, orderNumber)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderNumber,
		&i.Version,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboundOrderLines = `-- name: GetOutboundOrderLines :many
SELECT ol.id, ol.order_id, ol.sku_id, ol.pku_id, ol.requested_quantity, ol.fulfilled_quantity, s.id AS sku_uuid, s.name AS sku_name, p.unit_name
FROM outbound_order_lines ol
JOIN stock_keeping_units s ON ol.sku_id = s.id
JOIN sku_packaging_units p ON ol.pku_id = p.id
WHERE ol.order_id = $1
`

type GetOutboundOrderLinesRow struct {
	ID                int64
	OrderID           int64
	SkuID             int64
	PkuID             int64
	RequestedQuantity pgtype.Numeric
	FulfilledQuantity pgtype.Numeric
	SkuUuid           int64
	SkuName           string
	UnitName          string
}

func (q *Queries) GetOutboundOrderLines(ctx context.Context, orderID int64) ([]GetOutboundOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, getOutboundOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboundOrderLinesRow
	for rows.Next() {
		var i GetOutboundOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SkuID,
			&i.PkuID,
			&i.RequestedQuantity,
			&i.FulfilledQuantity,
			&i.SkuUuid,
			&i.SkuName,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOrderLineFulfillment = `-- name: IncrementOrderLineFulfillment :one
UPDATE outbound_order_lines
SET fulfilled_quantity = fulfilled_quantity + $2
WHERE id = $1 AND (fulfilled_quantity + $2) <= requested_quantity
RETURNING id, order_id, sku_id, pku_id, requested_quantity, fulfilled_quantity
`

type IncrementOrderLineFulfillmentParams struct {
	ID                int64
	FulfilledQuantity pgtype.Numeric
}

func (q *Queries) IncrementOrderLineFulfillment(ctx context.Context, arg IncrementOrderLineFulfillmentParams) (OutboundOrderLine, error) {
	row := q.db.QueryRow(ctx, incrementOrderLineFulfillment, arg.ID, arg.FulfilledQuantity)
	var i OutboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SkuID,
		&i.PkuID,
		&i.RequestedQuantity,
		&i.FulfilledQuantity,
	)
	return i, err
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, tenant_id, order_number, version, customer_name, status, priority, created_at, updated_at FROM outbound_orders
WHERE status = $1
ORDER BY priority DESC, created_at ASC
LIMIT $2 OFFSET $3
`

type ListOrdersByStatusParams struct {
	Status OrderStatus
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]OutboundOrder, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboundOrder
	for rows.Next() {
		var i OutboundOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderNumber,
			&i.Version,
			&i.CustomerName,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const packHandlingUnitContent = `-- name: PackHandlingUnitContent :one
INSERT INTO handling_unit_contents (
    handling_unit_id,
    allocation_id,
    packed_quantity
) VALUES (
    $1, $2, $3
)
RETURNING id, handling_unit_id, allocation_id, packed_quantity
`

type PackHandlingUnitContentParams struct {
	HandlingUnitID int64
	AllocationID   int64
	PackedQuantity pgtype.Numeric
}

func (q *Queries) PackHandlingUnitContent(ctx context.Context, arg PackHandlingUnitContentParams) (HandlingUnitContent, error) {
	row := q.db.QueryRow(ctx, packHandlingUnitContent, arg.HandlingUnitID, arg.AllocationID, arg.PackedQuantity)
	var i HandlingUnitContent
	err := row.Scan(
		&i.ID,
		&i.HandlingUnitID,
		&i.AllocationID,
		&i.PackedQuantity,
	)
	return i, err
}

const updateOutboundOrderStatus = `-- name: UpdateOutboundOrderStatus :one
UPDATE outbound_orders
SET
    status = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $3
RETURNING id, tenant_id, order_number, version, customer_name, status, priority, created_at, updated_at
`

type UpdateOutboundOrderStatusParams struct {
	ID      int64
	Status  OrderStatus
	Version int32
}

func (q *Queries) UpdateOutboundOrderStatus(ctx context.Context, arg UpdateOutboundOrderStatusParams) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, updateOutboundOrderStatus, arg.ID, arg.Status, arg.Version)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrderNumber,
		&i.Version,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
