// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbound_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboundOrder = `-- name: CreateOutboundOrder :one
INSERT INTO outbound_orders (
    order_number,
    customer_name,
    status,
    priority
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, order_number, customer_name, status, priority, created_at, updated_at
`

type CreateOutboundOrderParams struct {
	OrderNumber  string
	CustomerName pgtype.Text
	Status       OrderStatus
	Priority     int32
}

func (q *Queries) CreateOutboundOrder(ctx context.Context, arg CreateOutboundOrderParams) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, createOutboundOrder,
		arg.OrderNumber,
		arg.CustomerName,
		arg.Status,
		arg.Priority,
	)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboundOrderLine = `-- name: CreateOutboundOrderLine :one
INSERT INTO outbound_order_lines (
    order_id,
    sku_id,
    pku_id,
    requested_quantity,
    fulfilled_quantity
) VALUES (
    $1, $2, $3, $4, 0
)
RETURNING id, order_id, sku_id, pku_id, requested_quantity, fulfilled_quantity
`

type CreateOutboundOrderLineParams struct {
	OrderID           int64
	SkuID             int64
	PkuID             int64
	RequestedQuantity pgtype.Numeric
}

func (q *Queries) CreateOutboundOrderLine(ctx context.Context, arg CreateOutboundOrderLineParams) (OutboundOrderLine, error) {
	row := q.db.QueryRow(ctx, createOutboundOrderLine,
		arg.OrderID,
		arg.SkuID,
		arg.PkuID,
		arg.RequestedQuantity,
	)
	var i OutboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SkuID,
		&i.PkuID,
		&i.RequestedQuantity,
		&i.FulfilledQuantity,
	)
	return i, err
}

const deleteOutboundOrder = `-- name: DeleteOutboundOrder :execrows
DELETE FROM outbound_orders
WHERE id = $1
`

func (q *Queries) DeleteOutboundOrder(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutboundOrder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOutboundOrderByID = `-- name: GetOutboundOrderByID :one
SELECT id, order_number, customer_name, status, priority, created_at, updated_at FROM outbound_orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOutboundOrderByID(ctx context.Context, id int64) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, getOutboundOrderByID, id)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboundOrderByNumber = `-- name: GetOutboundOrderByNumber :one
SELECT id, order_number, customer_name, status, priority, created_at, updated_at FROM outbound_orders
WHERE order_number = $1 LIMIT 1
`

func (q *Queries) GetOutboundOrderByNumber(ctx context.Context, orderNumber string) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, getOutboundOrderByNumber, orderNumber)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboundOrderLines = `-- name: GetOutboundOrderLines :many
SELECT ol.id, ol.order_id, ol.sku_id, ol.pku_id, ol.requested_quantity, ol.fulfilled_quantity, s.id, s.name AS sku_name, p.unit_name
FROM outbound_order_lines ol
JOIN stock_keeping_units s ON ol.sku_id = s.id
JOIN sku_packaging_units p ON ol.pku_id = p.id
WHERE ol.order_id = $1
`

type GetOutboundOrderLinesRow struct {
	ID                int64
	OrderID           int64
	SkuID             int64
	PkuID             int64
	RequestedQuantity pgtype.Numeric
	FulfilledQuantity pgtype.Numeric
	ID_2              int64
	SkuName           string
	UnitName          string
}

func (q *Queries) GetOutboundOrderLines(ctx context.Context, orderID int64) ([]GetOutboundOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, getOutboundOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboundOrderLinesRow
	for rows.Next() {
		var i GetOutboundOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SkuID,
			&i.PkuID,
			&i.RequestedQuantity,
			&i.FulfilledQuantity,
			&i.ID_2,
			&i.SkuName,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOrderLineFulfillment = `-- name: IncrementOrderLineFulfillment :one
UPDATE outbound_order_lines
SET fulfilled_quantity = fulfilled_quantity + $2
WHERE id = $1 AND (fulfilled_quantity + $2) <= requested_quantity
RETURNING id, order_id, sku_id, pku_id, requested_quantity, fulfilled_quantity
`

type IncrementOrderLineFulfillmentParams struct {
	ID                int64
	FulfilledQuantity pgtype.Numeric
}

func (q *Queries) IncrementOrderLineFulfillment(ctx context.Context, arg IncrementOrderLineFulfillmentParams) (OutboundOrderLine, error) {
	row := q.db.QueryRow(ctx, incrementOrderLineFulfillment, arg.ID, arg.FulfilledQuantity)
	var i OutboundOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SkuID,
		&i.PkuID,
		&i.RequestedQuantity,
		&i.FulfilledQuantity,
	)
	return i, err
}

const listOrdersByStatus = `-- name: ListOrdersByStatus :many
SELECT id, order_number, customer_name, status, priority, created_at, updated_at FROM outbound_orders
WHERE status = $1
ORDER BY priority DESC, created_at ASC
LIMIT $2 OFFSET $3
`

type ListOrdersByStatusParams struct {
	Status OrderStatus
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByStatus(ctx context.Context, arg ListOrdersByStatusParams) ([]OutboundOrder, error) {
	rows, err := q.db.Query(ctx, listOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboundOrder
	for rows.Next() {
		var i OutboundOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.CustomerName,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboundOrderStatus = `-- name: UpdateOutboundOrderStatus :one
UPDATE outbound_orders
SET
    status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, order_number, customer_name, status, priority, created_at, updated_at
`

type UpdateOutboundOrderStatusParams struct {
	ID     int64
	Status OrderStatus
}

func (q *Queries) UpdateOutboundOrderStatus(ctx context.Context, arg UpdateOutboundOrderStatusParams) (OutboundOrder, error) {
	row := q.db.QueryRow(ctx, updateOutboundOrderStatus, arg.ID, arg.Status)
	var i OutboundOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.CustomerName,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
