// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skus.sql

package db

import (
	"context"
)

const getSomething = `-- name: GetSomething :one
SELECT id, sku_code, name, base_uom, is_discrete, requires_lot_tracking, attributes, created_at FROM stock_keeping_units LIMIT 1
`

func (q *Queries) GetSomething(ctx context.Context) (StockKeepingUnit, error) {
	row := q.db.QueryRow(ctx, getSomething)
	var i StockKeepingUnit
	err := row.Scan(
		&i.ID,
		&i.SkuCode,
		&i.Name,
		&i.BaseUom,
		&i.IsDiscrete,
		&i.RequiresLotTracking,
		&i.Attributes,
		&i.CreatedAt,
	)
	return i, err
}
