// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTask = `-- name: AssignTask :one
UPDATE warehouse_tasks
SET
    status = 'ASSIGNED',
    assigned_operator_id = $2
WHERE id = $1 AND status = 'PENDING'
RETURNING id, task_type, status, priority, sku_id, pku_id, lot_id, package_count, quantity, target_node_id, source_node_id, destination_node_id, order_line_id, allocation_id, assigned_operator_id, created_at, completed_at
`

type AssignTaskParams struct {
	ID                 int64
	AssignedOperatorID pgtype.Text
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) (WarehouseTask, error) {
	row := q.db.QueryRow(ctx, assignTask, arg.ID, arg.AssignedOperatorID)
	var i WarehouseTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.PackageCount,
		&i.Quantity,
		&i.TargetNodeID,
		&i.SourceNodeID,
		&i.DestinationNodeID,
		&i.OrderLineID,
		&i.AllocationID,
		&i.AssignedOperatorID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const cancelTask = `-- name: CancelTask :one
UPDATE warehouse_tasks
SET status = 'CANCELLED'
WHERE id = $1 AND status != 'COMPLETED'
RETURNING id, task_type, status, priority, sku_id, pku_id, lot_id, package_count, quantity, target_node_id, source_node_id, destination_node_id, order_line_id, allocation_id, assigned_operator_id, created_at, completed_at
`

func (q *Queries) CancelTask(ctx context.Context, id int64) (WarehouseTask, error) {
	row := q.db.QueryRow(ctx, cancelTask, id)
	var i WarehouseTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.PackageCount,
		&i.Quantity,
		&i.TargetNodeID,
		&i.SourceNodeID,
		&i.DestinationNodeID,
		&i.OrderLineID,
		&i.AllocationID,
		&i.AssignedOperatorID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeTask = `-- name: CompleteTask :one
UPDATE warehouse_tasks
SET
    status = 'COMPLETED',
    completed_at = now()
WHERE id = $1 AND status IN ('ASSIGNED', 'IN_PROGRESS')
RETURNING id, task_type, status, priority, sku_id, pku_id, lot_id, package_count, quantity, target_node_id, source_node_id, destination_node_id, order_line_id, allocation_id, assigned_operator_id, created_at, completed_at
`

func (q *Queries) CompleteTask(ctx context.Context, id int64) (WarehouseTask, error) {
	row := q.db.QueryRow(ctx, completeTask, id)
	var i WarehouseTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.PackageCount,
		&i.Quantity,
		&i.TargetNodeID,
		&i.SourceNodeID,
		&i.DestinationNodeID,
		&i.OrderLineID,
		&i.AllocationID,
		&i.AssignedOperatorID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createWarehouseTask = `-- name: CreateWarehouseTask :one
INSERT INTO warehouse_tasks (
    task_type,
    status,
    priority,
    sku_id,
    pku_id,
    lot_id,
    package_count,
    quantity,
    target_node_id,
    source_node_id,
    destination_node_id,
    order_line_id,
    allocation_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, task_type, status, priority, sku_id, pku_id, lot_id, package_count, quantity, target_node_id, source_node_id, destination_node_id, order_line_id, allocation_id, assigned_operator_id, created_at, completed_at
`

type CreateWarehouseTaskParams struct {
	TaskType          TaskType
	Status            TaskStatus
	Priority          int32
	SkuID             pgtype.Int8
	PkuID             pgtype.Int8
	LotID             pgtype.Int8
	PackageCount      pgtype.Numeric
	Quantity          pgtype.Numeric
	TargetNodeID      pgtype.Int8
	SourceNodeID      pgtype.Int8
	DestinationNodeID pgtype.Int8
	OrderLineID       pgtype.Int8
	AllocationID      pgtype.Int8
}

func (q *Queries) CreateWarehouseTask(ctx context.Context, arg CreateWarehouseTaskParams) (WarehouseTask, error) {
	row := q.db.QueryRow(ctx, createWarehouseTask,
		arg.TaskType,
		arg.Status,
		arg.Priority,
		arg.SkuID,
		arg.PkuID,
		arg.LotID,
		arg.PackageCount,
		arg.Quantity,
		arg.TargetNodeID,
		arg.SourceNodeID,
		arg.DestinationNodeID,
		arg.OrderLineID,
		arg.AllocationID,
	)
	var i WarehouseTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.PackageCount,
		&i.Quantity,
		&i.TargetNodeID,
		&i.SourceNodeID,
		&i.DestinationNodeID,
		&i.OrderLineID,
		&i.AllocationID,
		&i.AssignedOperatorID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWarehouseTaskByID = `-- name: GetWarehouseTaskByID :one
SELECT id, task_type, status, priority, sku_id, pku_id, lot_id, package_count, quantity, target_node_id, source_node_id, destination_node_id, order_line_id, allocation_id, assigned_operator_id, created_at, completed_at FROM warehouse_tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWarehouseTaskByID(ctx context.Context, id int64) (WarehouseTask, error) {
	row := q.db.QueryRow(ctx, getWarehouseTaskByID, id)
	var i WarehouseTask
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.Priority,
		&i.SkuID,
		&i.PkuID,
		&i.LotID,
		&i.PackageCount,
		&i.Quantity,
		&i.TargetNodeID,
		&i.SourceNodeID,
		&i.DestinationNodeID,
		&i.OrderLineID,
		&i.AllocationID,
		&i.AssignedOperatorID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listPendingTasks = `-- name: ListPendingTasks :many
SELECT id, task_type, status, priority, sku_id, pku_id, lot_id, package_count, quantity, target_node_id, source_node_id, destination_node_id, order_line_id, allocation_id, assigned_operator_id, created_at, completed_at FROM warehouse_tasks
WHERE status = 'PENDING'
ORDER BY priority DESC, created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingTasks(ctx context.Context, limit int32) ([]WarehouseTask, error) {
	rows, err := q.db.Query(ctx, listPendingTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WarehouseTask
	for rows.Next() {
		var i WarehouseTask
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Status,
			&i.Priority,
			&i.SkuID,
			&i.PkuID,
			&i.LotID,
			&i.PackageCount,
			&i.Quantity,
			&i.TargetNodeID,
			&i.SourceNodeID,
			&i.DestinationNodeID,
			&i.OrderLineID,
			&i.AllocationID,
			&i.AssignedOperatorID,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
